### ISSUE TITLE
Support Amazon SES instead of SendGrid?

### ISSUE THREAD

**Issue by jeremybmerrill** [themarshallproject/klaxon#10]
I think this would be doable by adding additional ENV VARS [here](https://github.com/themarshallproject/klaxon/blob/e83ee8b60df7308bbade2fc714107fe5afa2a542/config/environments/production.rb#L82-L88) to set the SMTP hostname and SMTP port; this would, I think, address the question of the Sendgrid dependency out of #8.

**Comment by jeremybmerrill** [comment]
To be clear, I'd be happy to work on this, if it's the right approach. I'd love to set this up on our (Docker-based) infra.

**Comment by ivarvong** [comment]
Yes, I'd like to support multiple SMTP providers. One way to do this (feedback welcome!) is by introducing a ENV var to prefix the SMTP setup vars.

As the default, we could set SMTP_PROVIDER=SENDGRID in `app.json` so the one-click deploy still works. 

Then use something like:
```ruby
# this is untested
provider = ENV['SMTP_PROVIDER']
address   = "#{provider}_ADDRESS"
user_name = "#{provider}_USERNAME"
password  = "#{provider}_PASSWORD"

ActionMailer::Base.smtp_settings = {
  :address        => address,
  :port           => '587',
  :authentication => :plain,
  :user_name      => user_name,
  :password       => password,
  :domain         => 'heroku.com',
  :enable_starttls_auto => true
}
```

...which would allow other providers. Thoughts?

@rdmurphy started a Dockerfile: https://github.com/themarshallproject/klaxon/pull/8 and I'm excited to get that figured out. I know @jeremyjbowers is also interested in Docker-based deployment.

**Comment by jeremybmerrill** [comment]
That's clever! I was planning on using @rdmurphy's image and stuff. I don't know from Heroku, so I'll take your word on the `app.json` stuff.

And @jeremyjbowers, I'll race you to deploy Klaxon on our infra. *3*... *2*... *1*...

(And assuming `address   = ENV["#{provider}_ADDRESS"]`, etc., right?)

**Comment by ivarvong** [comment]
@jeremybmerrill Good catch – I updated the snippet with the `ENV[]` that I forgot initially.

There are a couple unfortunate bugs right now (I did not setup `dependant_destroy`, for one, so bad things happen when things are deleted). If you all want to be early testers, I'd be forever grateful, but no worries if you want to wait until it stabilizes a bit more.

**Comment by rdmurphy** [comment]
I think this sounds awesome! 🎈

**Comment by ivarvong** [comment]
@jeremybmerrill generous PR (thanks!) has been merged to `develop`. Should we keep this issue open?

**Comment by jeremybmerrill** [comment]
I don't think so. I can imagine there are some weirder SMTP providers that might not work with this exact setup, but that bridge can be crossed then, right?

**Comment by ivarvong** [comment]
+1 for crossing the bridge then. Closing for now
