### ISSUE TITLE
A true admin status

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#106]
It would make sense to be able to remove users who have left an organization. Would you need users who are admins to have permission to clean out inactive users? And could those users Klaxons continue on?

**Comment by zstumgoren** [comment]
+1 to providing delete functionality in web interface for admin users.

@tommeagher In the interim, is dropping to rails console and manually deleting user the recommended strategy for removing user records?

**Comment by GabeIsman** [comment]
@zstumgoren Unfortunately that is currently the best way. You'll also want to delete any subscriptions that belong to the user.

**Comment by zstumgoren** [comment]
@GabeIsman Ok, makes sense. Appreciate the guidance. Would you all be interested in a PR for a rake task for this kind of thing? Perhaps with some basic documentation aimed at admins?

**Comment by GabeIsman** [comment]
@zstumgoren PRs are always appreciated. I think ideally we'd implement this functionality through the UI, but a rake task sounds like a reasonable stopgap! Documentation always and forever appreciated.

**Comment by tommeagher** [comment]
We ♥️ PRs & docs, @zstumgoren!

**Comment by zstumgoren** [comment]
+1 UI integration as ideal solution. I'll consult with my cohort @bobweston and see if we can push something back to you all, at least on the docs and rake front if not a first pass at the UI functionality. Any preferences on PR workflow?

**Comment by GabeIsman** [comment]
@zstumgoren PRs from your fork against our develop branch would be ideal!

**Comment by bobweston** [comment]
Hey Folks, I'll submit a pull request with this feature next week. I need to clean up a couple of front-end things. But the functionality is working.

**Comment by tommeagher** [comment]
@bobweston awesome. We'll be eager to see it.

**Comment by bobweston** [comment]
PR #121 has been submitted

**Comment by GabeIsman** [comment]
This is fixed by #121. Thanks a ton @bobweston and @zstumgoren!

**Comment by tommeagher** [comment]
🎉  Bravo! Thank you, @bobweston & @zstumgoren!
