### ISSUE TITLE
Invitations expire too quickly

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#111]
Invitation tokens are really just LoginTokens and expire in the same amount of time. They should last longer, and there should be a friendlier flow for handling expired tokens.

I propose adding a page for expired tokens which has language explaining the expiration and a button to re-login with the associated email pre-filled. There is potential for information leaking here, but it seems very likely that if you have a valid-but-expired login token for an email address, you already know what that email address is.

**Comment by GabeIsman** [comment]
#129 Dramatically improves the problem here (in that it prompts the user to re-login), but I think the experience is still confusing for first-time users. In particular these two issues seem most pressing:

1. Invitations, like login links, still expire in one hour. This is far too short. I propose seven days.
2. I think to the average user, the equivalence of logging in and receiving an invitation is probably confusing. I think we should make sure the language is clear in both scenarios.

To accomplish this we'll need to either add a function to `LoginToken`, `create_invitation` perhaps, which will set a longer expiration, and some kind of metadata in the payload `invitation: true` or some such. Then perhaps just a small tweak to the language on `sessions#expired` based on the type of token.

**Comment by GabeIsman** [comment]
@bobweston This is hopefully a bit clearer version of what I was saying in #129.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 7 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
