### ISSUE TITLE
Email address check is case-sensitive on login but not on user creation

### ISSUE THREAD

**Issue by myersjustinc** [themarshallproject/klaxon#114]
When I attempt to log in to our internal Klaxon instance, I have to type my email address with the exact capitalization that's shown in `/users`. When I attempt to log in with the same email address but with different capitalization, I get an "Email Not Found" error.

The `User` model [does a case-insensitive check for uniqueness](https://github.com/themarshallproject/klaxon/blob/0a645bd79b84d1a874c1676cc5c5dd03ce8afeef/app/models/user.rb#L2), but `SessionsController#create` [uses the email address exactly as the user provided it](https://github.com/themarshallproject/klaxon/blob/0a645bd79b84d1a874c1676cc5c5dd03ce8afeef/app/controllers/sessions_controller.rb#L8).

Seems like case-insensitivity is the way to go. Happy to take an initial stab at updating the controller, unless anyone else gets to it first.

**Comment by GabeIsman** [comment]
@myersjustinc Ah nice catch. I agree with your assessment. Should just be case-insensitive everywhere. Please do take a stab at updating! Thanks.

**Comment by GabeIsman** [comment]
👍  Thanks!
