### ISSUE TITLE
couldn't deploy to Heroku

### ISSUE THREAD

**Issue by samanthasunne** [themarshallproject/klaxon#117]
Followed the installation directions and got this error message on Heroku:

![screen shot 2017-05-09 at 6 55 13 pm](https://cloud.githubusercontent.com/assets/1383000/26068906/c87dfede-3964-11e7-84a0-9217ca958293.png)

Tried again, and got this error log:

[-.txt](https://github.com/themarshallproject/klaxon/files/1001766/-.txt)

I didn't mess with any of the fields except admin-email, so I'm not sure what's up.

**Comment by GabeIsman** [comment]
@samanthasunne Thanks for reporting! I'll look into it. Looks like we might need to update the ruby version we're using.

**Comment by ivarvong** [comment]
For what it's worth, I got a transient error deploying an unrelated app to Heroku around the same time. (No idea if related.)

**Comment by GabeIsman** [comment]
@samanthasunne Confirmed that upgrading the Ruby version fixed the problem. Give it another shot, and let us know if you have any more trouble!

@ivarvong Good to know. I was able to reproduce this twice at different times, so it seems to have been a real failure.

**Comment by samanthasunne** [comment]
That fixed it. Thanks for the quick response!
