### ISSUE TITLE
ruby version requirement on 0.2.4

### ISSUE THREAD

**Issue by bobweston** [themarshallproject/klaxon#119]
Hey Folks,

I see the ruby version has been bumped to ruby-2.3.4. I'm wondering if is a requirement for Klaxon or if you folks were simply bumping things to a later version.

I'm just trying to get a sense of whether we need to add this new version of ruby or can continue using the older version.

I appreciate the guidance.

**Comment by GabeIsman** [comment]
@bobweston You can absolutely continue with the older version. We just bumped it up to keep pace with Heroku support. The code in no way depends on 2.3.4 (although deployment to Heroku now does).
