### ISSUE TITLE
Enhance snapshots?

### ISSUE THREAD

**Issue by zzolo** [themarshallproject/klaxon#122]
I am wondering if the following is a good idea and might be worth making a pull request for:

In addition to snapshotting content, it would be nice to have an image snapshot of the page and/or a version of the markup of the page since there can be details in the markup that are important.

If this seems like a decent idea, I can try to work on it.

**Comment by zzolo** [comment]
I think I missed the whole snapshot thing in the documentation.  I'll look into that more and see if it does what I expect.  Thanks!

**Comment by zzolo** [comment]
Updated original comment.

**Comment by tommeagher** [comment]
Hey Alan @zzolo! Correct me if I'm wrong, @GabeIsman & @ivarvong, but right now every time the page you're watching changes, Klaxon captures the HTML of the whole page. Klaxon then only sends an alert (Slack/email) if the hash of the text in the chosen CSS selector has changed. All of which is to say that it's already capturing the markup of the whole page, it's just not shown to users. 

If you think it'd be useful, we'd probably be open to PRs with a UI to explore those changes over time, depending on what you have in mind.

**Comment by zzolo** [comment]
Oh, that's is cool.  Yeah, I would think it might be interesting to see the markup or markup diff, for instance, there's a page I am looking at that changes its icon image, but there isn't text change.

I do think an image snapshot would be good as an archive and a way to see a more visual version of what the page looked like.

**Comment by ivarvong** [comment]
Hi @zzolo! The `PageSnapshot` model holds the full HTML of the page at time of snapshot. Exposing the markup or markup diff would be straightforward.

To your example use-case, though: a page snapshot is *not* created if the hash of the polled page hasn't changed. Said another way, a snapshot for a page is not created every 10 minutes, rather only if the page has changed, based on the hash of the HTML within the CSS selector. This is to prevent a lot of duplicate snapshots, but at the cost of not allowing for retroactive analysis of pages. Here's [PollPage](https://github.com/themarshallproject/klaxon/blob/develop/app/models/poll_page.rb#L3
), where the check happens.

One design goal was to make Klaxon useful without a lot of setup, specifically creating S3 credentials. Creating a snapshot every 10 min, whether HTML or a screencap, is of course totally possible, but would need to have a storage backend outside of Postgres. 

Perhaps a future version of Klaxon will have an on-ramp toward these capabilities: begin with Heroku-only, using only Postgres for storage, and later on enable most features (headless Chrome for running JS, creating screenshots).

**Comment by zzolo** [comment]
Yeah, I don't think there's a reason to store a snapshot if Klaxon doesn't think a change has occurred, I am mostly just looking for some further archive information being available (i.e. the markup and a screenshot).  I think it could be possible (maybe not ideal) to store a screenshot in Postgres.

**Comment by immewnity** [comment]
A similar way of achieving this could be submitting the page to the Internet Archive's Wayback Machine if a change occurred (prepending "https://web.archive.org/save/" to a URL will do just that). Would be awesome to have this as a checkbox option on each tracked page!

**Comment by tommeagher** [comment]
#337 displays the page as captured (minus some assets and css), which partially addresses this issue. It does not show the full markup diff that @zzolo really needed in his original issue.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 7 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
