### ISSUE TITLE
Edit user's subscriptions from /user/edit

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#128]
It would be useful to be able to unsubscribe from pages en masse on /users/edit.

**Comment by bobweston** [comment]
I'll take a crack at this

**Comment by bobweston** [comment]
Hey @GabeIsman,

What do you think about adding checkboxes next to the user's list of subscriptions, along with an uncheck all option/button? We could then uncheck a single box (or all) to trigger an unsubscribe action.

**Comment by GabeIsman** [comment]
@bobweston That's pretty much exactly what I had in mind. The only potential snag I see with this is that because there is no notion "inactive subscription" currently, when you uncheck the box, the item will disappear (immediately or on page load). That might be unintuitive. But I'm not sure if it will actually be a problem I suspect we shouldn't worry about it for now.

**Comment by tommeagher** [comment]
Pretty certain this was dealt with in #131. Will close this issue as a result, but let me know if we need to reopen it.
