### ISSUE TITLE
Bookmarklet doesn't work in Firefox

### ISSUE THREAD

**Issue by jeremybmerrill** [themarshallproject/klaxon#13]
````
ReferenceError: event is not defined      inject:98:9
````
I assume that the solution is just to add `event` as an argument here: 
https://github.com/themarshallproject/klaxon/blob/master/app/views/embed/inject.js.erb#L97

but I'm not sure.

Worked fine in Chrome on my install.

**Comment by ivarvong** [comment]
thanks. i wanted to avoid jquery here, but appear to have forgotten my non-chrome javascript things. will look into this tomorrow.

**Comment by jeremybmerrill** [comment]
I added "event" as an argument and it works fine now (no jQuery needed). I guess Chrome automatically adds `event` as an argument, but Firefox doesn't?

**Comment by rdmurphy** [comment]
`event` is a global in Chrome and IE (AKA it's on `window`), Firefox doesn't sneak it in. My guess that's what's causing this issue.

**Comment by ivarvong** [comment]
Still doesn't work, but the `evt` arg is there at least. That was... silly. https://github.com/themarshallproject/klaxon/commit/326aaec64352ccf50043f2521561e7fcfd4f8ecd#diff-845065c76fc209c11afe4d3b4363283cR99

**Comment by ivarvong** [comment]
The bookmarklet needs definitely needs some work, but the event handler argument bug is fixed (in master: https://github.com/themarshallproject/klaxon/blob/master/app/views/embed/inject.js.erb#L99). I'm going to close this for now, but feel free to open other bookmarklet-related issues separately.
