### ISSUE TITLE
Configurable outbound email?

### ISSUE THREAD

**Issue by rdmurphy** [themarshallproject/klaxon#14]
Not 100% sure if the bug is on my end or not — I was trying to set up Klaxon to use the Tribune's SES account, and it threw an unverified email address error.

```sh
[ActiveJob] [ActionMailer::DeliveryJob] [f9740ecf-5e14-477d-932d-418a9e4bfaa2] Performed ActionMailer::DeliveryJob from Inline(mailers) in 1621.73ms
Completed 500 Internal Server Error in 1694ms (ActiveRecord: 6.3ms)

Net::SMTPFatalError (554 Message rejected: Email address is not verified.
):
  app/controllers/sessions_controller.rb:11:in `create'
```

The error makes sense — our SES account hasn't verified `no-reply@newsklaxon.com`, so it turns it away. Should it be possible to [set the email address to use](https://github.com/themarshallproject/klaxon/blob/develop/app/mailers/application_mailer.rb#L3)? Is that something else that can be passed into ActionMailer's config? I was able to get it to work by switching out that line with the email I originally tried.

**Comment by rdmurphy** [comment]
Will ping @jeremybmerrill on this one too, not sure if he has hit this yet.

**Comment by jeremybmerrill** [comment]
yes, that's what you need to do, this is what I did: https://github.com/newsdev/klaxon/commit/a498f15261965de2a7aae01c82471719dad3b633

**Comment by jeremybmerrill** [comment]
there may be a better way to do it, but that change made it work for me.

**Comment by ivarvong** [comment]
yep, this totally makes sense. i'll extract this to ENV with a fallback

**Comment by ivarvong** [comment]
The mailer default sender now comes from `ENV['MAILER_FROM_ADDRESS']` (https://github.com/themarshallproject/klaxon/commit/13940887385d778079790e5747d6018f9fe334c2)

Thoughts?

**Comment by jeremybmerrill** [comment]
👍
