### ISSUE TITLE
Run JavaScript before taking snapshot

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#140]
This would allow watching of client-rendered pages. Would require outsourcing scraping to PhantomJS or similar, which would add to complexity. Definitely seems worth it though.

**Comment by chrismp** [comment]
Has this feature been implemented?

**Comment by tommeagher** [comment]
Hi @chrismp, no, this feature has not been implemented. We're hoping someone will want to give it a shot. We accept pull requests.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (over 6 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
