### ISSUE TITLE
"Deploy to Heroku" one-click halts at environment configuration

### ISSUE THREAD

**Issue by justinallen** [themarshallproject/klaxon#141]
Trying to follow the instructions on Github, the one-click install initializes, makes it through "create app" and then halts at environment configuration.

First:

![screen shot 2018-02-06 at 11 57 24 am](https://user-images.githubusercontent.com/1314318/35881314-484e25ec-0b35-11e8-8493-ee0c19599e74.png)

Then:

![05_error](https://user-images.githubusercontent.com/1314318/35881383-7b69dbe2-0b35-11e8-8791-9c85b9e3fce1.png)

All fields (app name, admin email) filled out correctly. Am I doing something wrong?

**Comment by justinallen** [comment]
**Update:** 

Tried again after a few hours and the error magically went away, sailed through the build without a problem.

![06_ok](https://user-images.githubusercontent.com/1314318/35889368-1ef29d3e-0b50-11e8-994a-f2ebc3e3deb6.png)

Not sure what was going on, maybe some downtime on Heroku's end.

**Comment by tommeagher** [comment]
Thanks for flagging @justinallen. Glad to hear it resolved itself. Let us know how it goes as you get rolling with Klaxon.
