### ISSUE TITLE
Instructions for deployment to EC2

### ISSUE THREAD

**Issue by brentajones** [themarshallproject/klaxon#145]
Would love to have some instructions for deploying to EC2.

**Comment by tommeagher** [comment]
Great idea. I’ll ask our Twitter followers if anyone wants to take a swing at this.

**Comment by anthonydb** [comment]
@brentajones Wondering whether you ever got help with this question?

**Comment by tommeagher** [comment]
@anthonydb I don’t think we ever got any takers on this. If you and Brent would be willing to give this a shot, we’d love to include the instructions in the repo here.

**Comment by brentajones** [comment]
@anthonydb No, I hadn't heard anything about it. It's been fairly low on my list as I'm not very fluent in either Rails or Docker and I'm not sure how much of those I'll need to pick up in order to make progress.

I will likely have more time to work on larger projects / newsroom tools soon, and I'm still very interested in implementing this for the newsroom, so it's still possible I'll grapple with it at some point if some generous person hasn't done it by then.

**Comment by anthonydb** [comment]
@tommeagher @brentajones If I get a chance to set this up in a few weeks on EC2 I will definitely share what I learn. Thanks!

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 7 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
