### ISSUE TITLE
Display version numbers in help section

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#147]
This'll make it easier for users to know what version of Klaxon they're running and whether they need to upgrade to a newer release.

**Comment by tommeagher** [comment]
Could deal with it like this, perhaps. https://stackoverflow.com/questions/14583282/heroku-display-hash-of-current-commit-in-browser 

Could be a post-commit hook that sets the value of `git tag | tail -n 1` to an env var we could display on the help page.

**Comment by tommeagher** [comment]
Could deal with it like this, perhaps. https://stackoverflow.com/questions/14583282/heroku-display-hash-of-current-commit-in-browser 

Could be a post-commit hook that sets the value of `git tag | tail -n 1` to an env var we could display on the help page.

**Comment by tommeagher** [comment]
On further thought, the post-commit hook doesn't make sense, but could put this as a shell task in the Rakefile.

**Comment by tommeagher** [comment]
It seems this is what I'm looking for: https://github.com/themarshallproject/klaxon/blob/0bd045e1baab92413b41d7de6df02499a35e57bb/postdeploy.sh

**Comment by ivarvong** [comment]
With Heroku, this is an option: https://devcenter.heroku.com/articles/dyno-metadata#usage

With Docker, the system (probably CI) generating the container artifact is perhaps the right place for this kind of thing

**Comment by tommeagher** [comment]
Hi, @ivarvong! 👋

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 6 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
