### ISSUE TITLE
Klaxon unable to track websites with a login prompt/auth

### ISSUE THREAD

**Issue by alanhovorka** [themarshallproject/klaxon#148]
I have a weird one here. 

I'm trying to use Klaxon to track agenda postings for a university. 

I have setup Klaxon to track this page and it's not returning changes. The page is changing daily, but Klaxon isn't telling me that. It appears the problem may be the login prompt when the page loads. 

https://committees.uwsp.edu/facsen/agendas/SitePages/Home.aspx

![image](https://user-images.githubusercontent.com/12141291/39010796-46638f0a-43d5-11e8-920c-4c1eea8d1c11.png)
![image](https://user-images.githubusercontent.com/12141291/39010835-5ef72c34-43d5-11e8-9333-82f8edd186fa.png)

The thing is, you don't need credentials. If you hit cancel, you're able to go to the page. This is not a bug in the website, apparently. 

A note from Jesse Hazel, Courier-Journal:

> Yeah, it's definitely the authentication. If you curl that page (or just open source in browser and refresh it), it gives a different page with no data which is prob what Klaxon is seeing.
>Put this in a browser bar, it's likely what Klaxon is seeing: `view-source:https://committees.uwsp.edu/facsen/agendas/SitePages/Home.aspx`

Any idea on how to get Klaxon not to hang on the login screen when it loads?

**Comment by tommeagher** [comment]
Alan, that Asp.NET login is what's throwing it off. Klaxon, unfortunately, isn't designed to deal with more complex scrapes like those this would require. Klaxon is really best suited for very basic sites where the HTML is visible without any user action. For this, you'd have to create a custom program to scrape it.

**Comment by GabeIsman** [comment]
This seems like it would be a good use case for a custom scraper. A feature we intend to support eventually: https://github.com/themarshallproject/klaxon/issues/46.
