### ISSUE TITLE
Add bookmarklet instructions to README.md - or add link to help.md

### ISSUE THREAD

**Issue by chill-fpraz** [themarshallproject/klaxon#152]
The bookmarklet functionality of Klaxon is an important concept that is missing in the README.md instructions for deployment. It might help new users if the instructions contained in help.md were included or linked from README.md. My apologies if this has already been addressed in a previous issue. Thank you!

**Comment by tommeagher** [comment]
Hi @chill-fpraz, thanks for this. There is a link to help.md in this sentence high up: "[If you need help using Klaxon once it's already been set up, [you can find it here.](https://github.com/themarshallproject/klaxon/blob/master/data/help.md)]". But we got similar feedback from another user recently, so we agree this could be improved. Do you have any suggestions on where to put this or how to phrase it? (we also accept pull requests :)

**Comment by tommeagher** [comment]
Closed by #153
