### ISSUE TITLE
SSL errors are silently ignored

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#154]
When OpenSSL rejects a website's certificate, the page fetch fails and no snapshots are taken until the situation is resolved. Possible solutions:

1) Surface these errors somehow, maybe via the subscription channels. The downside to this is that there isn't really a solution. Sometimes you will want to monitor a page with an invalid SSL certificate, and you simply can't, as it currently stands.
2) Ignore SSL errors altogether. This has some potential downsides in that we're not getting the benefit of transport security, where available. However, it's hard to imagine a scenario where this would really be relevant. My tendency is to think that its more important to be able to monitor pages with invalid certificates, than to protect against deliberate tampering.

In an ideal world we would implement both. There are a couple of related conditions that we should have a means of notifying subscribers about: #53 when a page starts redirecting (possibly due to SSL implementation), #85 when a page's structure changes so much that your selector no longer matches anything.

**Comment by immewnity** [comment]
Not too skilled in Ruby, Rails, or even GitHub, but I think this'll do what's in option 2.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 6 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
