### ISSUE TITLE
Empty selector field does nothing

### ISSUE THREAD

**Issue by alaskapublic** [themarshallproject/klaxon#155]
Can you change an empty selector field to imply that Klaxon should watch the HTML document body?

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 6 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
