### ISSUE TITLE
Suggestion: Use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [themarshallproject/klaxon#156]
Would you be up for automatically creating Dependency update PRs? I built [Dependabot](https://dependabot.com) to do that and it's free for open source.

I think it would save you a bit of time and help keep klaxon up-to-date, but I also have an ulterior motive for asking: I'm keen to get more open source apps using it so I can use the data on the CI runs for dependency updates to find bugs in new releases and point the maintainers to the failing CI run as a reproduction step.

Having well-tested open-source apps like klaxon use it should enable it to do awesome things, like automatically test release candidates of Rails and report back on any breakages, etc.

What do you reckon?

**Comment by tommeagher** [comment]
@greysteil thanks for the suggestion. We weren't familiar with Dependabot before. We're interested in giving it a try.

**Comment by greysteil** [comment]
Awesome! I'll try and help out with some of the initial PRs. 🙂
