### ISSUE TITLE
Configurable time zone

### ISSUE THREAD

**Issue by rdmurphy** [themarshallproject/klaxon#16]
Let me know if we're approaching config overload, but should `config.time_zone` also be an ENV variable?

https://github.com/themarshallproject/klaxon/blob/e83ee8b60df7308bbade2fc714107fe5afa2a542/config/application.rb#L26

Just noticed our version is an hour ahead. 😁

**Comment by arossback** [comment]
Should this be configurable by user?

**Comment by rdmurphy** [comment]
Yeah, I that would make sense. No guarantees that every person on a team is in the same TZ.

**Comment by ivarvong** [comment]
@rdmurphy What if we extract all these config things to providers in https://github.com/themarshallproject/klaxon/blob/master/app/models/app_setting.rb – timezone, email sender address, etc, with fallbacks for the one-click Heroku use-case. I'm happy to do this in the next few days.

Per-user timezone totally makes sense, but maybe after we've stabilized the initial feature set?

**Comment by rdmurphy** [comment]
Yeah, I think that'd work. And no rush! Everything is standing up fine with the current set up (at least for our test version).

**Comment by ivarvong** [comment]
Models are loaded when `config/application.rb` runs, so I came up with: https://github.com/themarshallproject/klaxon/commit/621550f0bf9bece519b95bbbbaaa31448b323de2 Feedback welcome.

**Comment by ivarvong** [comment]
Does `ENV['TIME_ZONE']` work for you @rdmurphy?

**Comment by rdmurphy** [comment]
Doh, sorry for the delay. Sounds good, @ivarvong!
