### ISSUE TITLE
Not a valid Heroku application?

### ISSUE THREAD

**Issue by bzigterman** [themarshallproject/klaxon#206]
Running into another error. Unfortunately, Heroku isn't letting me copy and paste from their website on my iPad, but I've attached a screenshot with the end of the build log. I'll try again on another computer later.

![bc2976ee-7cf8-44d7-9996-dcc0064efa9a](https://user-images.githubusercontent.com/3458463/46097077-81aa4c00-c186-11e8-820a-3421ddf40f9d.jpeg)

**Comment by GabeIsman** [comment]
Sorry @bzigterman! Too hasty on the QA. Should be fixed now! I was just able to successfully deploy.
