### ISSUE TITLE
Fails to install with docker

### ISSUE THREAD

**Issue by jwhazel** [themarshallproject/klaxon#210]
_I've edited my original post to make this more concise_
There are currently at least 2 issues preventing Klaxon from working out of the box with Docker.

1.) This needs to be updated to 2.4.4 to match the gemfile: https://github.com/themarshallproject/klaxon/blob/f7c5c976b28ac6b0929fa6109193ddcd7a1cfc50/Dockerfile#L1
2.) This needs to be set to `production`, otherwise database.yml will use localhost which prevents the app from connecting to the database container:
https://github.com/themarshallproject/klaxon/blob/f7c5c976b28ac6b0929fa6109193ddcd7a1cfc50/docker-compose.override.yml#L12

After fixing these 2 issues, you can successfully complete the steps in DOCKER.md without any errors. However there is no html output from the server or any headers being sent. It's like the server isn't even running. Are there any other modifications that need to be made to get it to working in docker?

**Comment by tommeagher** [comment]
@jwhazel thank you for flagging this issue. We don't use Docker at The Marshall Project, so this isn't something I personally have experience with. 

I'm hoping some of our users who do rely on Docker, like @rdmurphy or @AlJohri can help advise on what else we'll need to do with https://github.com/themarshallproject/klaxon/blob/develop/DOCKER.md and https://github.com/themarshallproject/klaxon/blob/develop/Dockerfile to get this working again.

**Comment by rdmurphy** [comment]
Hey @jwhazel! I don't actually use the `docker-compose.yml` file myself, but I think standard practice is not that the in-project `docker-compose.yml` file is intended to be used for a production instance, but as a quick way to spin up a dev instance as we note at the top of the [`DOCKER.md`](https://github.com/themarshallproject/klaxon/blob/develop/DOCKER.md). (You may be correct it flat out isn't working right now, but I personally have never used it.)

I don't believe that The Marshall Project is actively maintaining an instance of Klaxon on Docker Hub, so there's kind of a missing piece here — what I *would* normally recommend is to use the prepared image and insert it into your own customized-to-you deployment setup. We use GCS and Kubernetes — so we have our image for our forked version of Klaxon (which is a few versions behind 😬) in a private Google Container Registry.

You **are** right though that the Gemfile Ruby version and the Dockerfile Ruby version should be in sync.

**Comment by jwhazel** [comment]
Thanks for the input. Hopefully you can understand my confusion here since all the components for docker were included in this project, I assumed that it was supported. 

I will continue to poke at it and happy to make PR's along the way. I just want to get it running first before I make any.

**Comment by AlJohri** [comment]
Hi! Sorry, I don't currently have this deployed anywhere but happy to help debug if needed. I have a slightly different take from @rdmurphy here.

The `docker-compose.override.yml` is almost always used for local development only. The barebones `docker-compose.yml` can be used for production- all the environment variables are empty in that file.

You can do something like this to run just the `docker-compose.yml` skipping the `docker-compose.override.yml`:

```
RAILS_ENV=production OTHERVAR=OTHERVAL... docker-compose --file docker-compose.yml up app
```

>However there is no html output from the server or any headers being sent. It's like the server isn't even running. Are there any other modifications that need to be made to get it to working in docker?

Sorry, I'd have to dig in further to see what's going on there.

**Comment by rdmurphy** [comment]
To the `docker-compose.override.yml` thing — I kinda fudged what I said, I did mean to refer to the `override.yml` file, I think we're on the same page, actually!

Per the [docker-compose docs](https://docs.docker.com/compose/extends/#example-use-case), another option is to create your own override that sets those environment variables for you and bypass the provided override entirely.

```sh
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
```
