### ISSUE TITLE
ROLLBACK in logs

### ISSUE THREAD

**Issue by AnalogJ** [themarshallproject/klaxon#230]
Hi,
I've attempted to get started with Klaxon via Docker and Heroku.
In both cases I've gotten everything working to the point of adding new sites to watch, but when running `bundle exec rake check:all` I get the following `ROLLBACK` messages:

```
Ignite:klaxon jason$ heroku run bundle exec rake check:all --app klaxon-mediadepot
Running bundle exec rake check:all on ⬢ klaxon-mediadepot... up, run.1002 (Free)
  AppSetting Exists (1.6ms)  SELECT  1 AS one FROM "app_settings" WHERE "app_settings"."key" = $1 LIMIT $2  [["key", "default_host"], ["LIMIT", 1]]
  AppSetting Load (1.2ms)  SELECT  "app_settings".* FROM "app_settings" WHERE "app_settings"."key" = $1 LIMIT $2  [["key", "default_host"], ["LIMIT", 1]]
[SUCCESS] Setting default_url_options[:host] = 'klaxon-mediadepot.herokuapp.com'
  Page Load (1.7ms)  SELECT "pages".* FROM "pages"
downloading url=https://www.1188missionapts.com/floorplan/1x1/ for page.id=1
  PageSnapshot Load (12.0ms)  SELECT  "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."page_id" = $1 AND "page_snapshots"."sha2_hash" = $2 LIMIT $3  [["page_id", 1], ["sha2_hash", "b6c1d76d3ed89fb61622d202246c9412f5cde474c1553d06ae21f22f568b7003"], ["LIMIT", 1]]
   (8.4ms)  BEGIN
  PageSnapshot Update (6.4ms)  UPDATE "page_snapshots" SET "updated_at" = $1 WHERE "page_snapshots"."id" = $2  [["updated_at", "2018-12-23 22:11:18.106278"], ["id", 1]]
   (4.0ms)  COMMIT
page id='1' has not changed
  Page Load (1.6ms)  SELECT "pages".* FROM "pages"
  PageSnapshot Load (4.0ms)  SELECT  "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."page_id" = $1 ORDER BY created_at DESC LIMIT $2  [["page_id", 1], ["LIMIT", 1]]
  PageSnapshot Load (2.9ms)  SELECT  "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."page_id" = $1 AND "page_snapshots"."id" != $2 AND (created_at < '2018-12-23 22:03:57.934573') ORDER BY created_at DESC LIMIT $3  [["page_id", 1], ["id", 1], ["LIMIT", 1]]
  Change Load (4.2ms)  SELECT  "changes".* FROM "changes" WHERE "changes"."before_id" IS NULL AND "changes"."after_type" = $1 AND "changes"."after_id" = $2 ORDER BY "changes"."id" ASC LIMIT $3  [["after_type", "PageSnapshot"], ["after_id", 1], ["LIMIT", 1]]
   (2.0ms)  BEGIN
  PageSnapshot Load (8.7ms)  SELECT  "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (1.5ms)  ROLLBACK
```

Any advice would be appreciated.

**Comment by GabeIsman** [comment]
Hey AnalogJ,

I'm not sure I've seen that behavior before, but my guess would be that it only happens in the case when the page you're watching hasn't changed yet. I like to use https://www.timeanddate.com/worldclock/usa/new-york as a test page. Give that a try and see if the problem persists. It's odd that there's no exception being thrown (what usually triggers a rollback), which either means that it's getting swallowed somewhere, or is some intended rails behavior that I don't totally understand.

Let me know if the problem persists!

**Comment by tommeagher** [comment]
Hi @AnalogJ. I'm going back through and culling old issues that are no longer active. Did you get this problem sorted out? Can we close this issue?

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 6 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
