### ISSUE TITLE
Update bookmarklet installation instructions

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#235]
Chrome no longer allows a user to drag and drop a bookmark. We also disabled right clicking on the bookmarklet to copy the javascript, so this needs to be addressed for new users to get started.

**Comment by asvc** [comment]
Just FYI, works as expected on the latest stable FF & FF ESR. Klaxon domain needs to be whitelisted though.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (over 5 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
