### ISSUE TITLE
not receiving authentication email

### ISSUE THREAD

**Issue by benzipperer** [themarshallproject/klaxon#237]
I'm unfortunately not receiving the authentication email after entering the admin email address in the Klaxon login page.

After deploying the app to Heroku following the readme instructions, I open the app, and enter my email address on the red "You'll know first" login page. I don't receive an email (after about an hour).

What should I look at to diagnose why this is failing?

**Comment by tommeagher** [comment]
Hi Ben, did you include a list of email addresses for administrators when you created the app in Heroku? 

https://github.com/themarshallproject/klaxon#lets-do-this
"Scroll down to the “* Admin_emails” field, add a comma-separated list of email addresses for your newsroom’s Klaxon administrators. These administrators will be able to create accounts for any user in your organization, as well as configure various Klaxons and integrations with services like Slack."

If you did follow that step, is it possible you mistyped your email address? 
You can look in Heroku at the config variables in your app's settings to see what is there: https://dashboard.heroku.com/apps/[[your-apps-name-here]]/settings

Did that all line up?

**Comment by benzipperer** [comment]
Hi Tom, thanks for your help. I think I did this correctly, or at least the ADMIN_EMAILS config var looks correct. It is a single email address (no commas).

Are there other config variables I should have set but possibly didn't?

I also tried deploying Klaxon again, encountering the same problem.

**Comment by GabeIsman** [comment]
Hey Ben,

I just spooled up an instance and noticed that my SendGrid (our email provider) account was "suspended." Still investigating why that might be, but you can check if the same issue is affecting you by clicking on SendGrid in the "Resources" tab of the heroku app.

**Comment by benzipperer** [comment]
Ah, thanks, I have the same problem. This is the first time I have used SendGrid.

**Comment by GabeIsman** [comment]
Yea, I wonder if they've changed their policies about free accounts or something. I've contacted their support (who knows how long that will take). I'll update here with whatever I find out. Sorry for the inconvenience!

**Comment by benzipperer** [comment]
The suspended SendGrid account turned out to be the problem. Once it was reinstated (after contacting customer support) the problem was resolved.
