### ISSUE TITLE
SendGrid now requires account verification

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#238]
SendGrid no longer works right out of the box. You have to contact their support to get your account activated. This adds an annoying step to the setup, so we should consider if there's another email vendor that works better for us.

See #237 for some more detail.

**Comment by stungeye** [comment]
I set up a Klaxon instance today using the "Deploy to Heroku" button. 

SendGrid seemed to work out-of-the-box without any work on my behalf. 

Just thought I'd let you know. Very slick deploy process. I was impressed!

**Comment by GabeIsman** [comment]
Thanks for the heads up @stungeye! Glad it's working. We do try to make it easy.

**Comment by stungeye** [comment]
@GabeIsman I've gotta say it's the nicest install process for an open source project that I've ever come across!

**Comment by Sanchovilla** [comment]
Hello!  I've clicked on the Sendgrid link to have my email confirmed but it says its a broken link and I'm getting an, "Access to Sendgrid Denied HTTP 403 Error."  Is there another way around this?  I've set-up a free account on Sendgrid but not sure how to make the connection between the two.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (5 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
