### ISSUE TITLE
Not possible to delete a watched page

### ISSUE THREAD

**Issue by anderser** [themarshallproject/klaxon#24]
Maybe I am just not finding the button, but is there no way of deleting a site from the watch list? 
I had to delete using SQL query. 
Looks like there is a destroy endpoint https://github.com/themarshallproject/klaxon/blob/master/app/controllers/pages_controller.rb#L68-L72, but maybe just button missing? 
My Ruby knowledge is extremely limited, so no pull request for now :)

(BTW great project!)

**Comment by tommeagher** [comment]
Hi Anders! Thanks for flagging this. This is an issue we're aware of, and it's one of the ones that @ivarvong and @arossback are working on as we make the final touches on a usable release. Our hope is to have that wrapped up in the next week or so for newsroom developers to continue testing. This is super helpful feedback, though, and we appreciate you filing the issue. If you want to try Klaxon once the first release is finished, we'd love to get more feedback and bug reports from you. 
Thanks again!

**Comment by GabeIsman** [comment]
Fixed in develop.
