### ISSUE TITLE
Google Groups

### ISSUE THREAD

**Issue by ilopata1** [themarshallproject/klaxon#269]
When I try to access the Google Group referenced in the README, I receive a message that I do not have permission to access the content.  I can find no way to sign up to participate in the group.

(My real issue is that when I add some pages to watch there is no initial snapshot taken and I need guidance on how to diagnose and resolve.)

**Comment by tommeagher** [comment]
Hi, @ilopata1, it looks like there was an issue with our Groups setting. Try to subscribe to the group now.

**Comment by ilopata1** [comment]
That worked.  Thanks
