### ISSUE TITLE
Suggestion: add Papertrail as a default add-on for Heroku deploys

### ISSUE THREAD

**Issue by tomcardoso** [themarshallproject/klaxon#276]
The first thing I do whenever I spin up any kind of Heroku instance is add the free-tier Papertrail add-on ("Choklad," I think it's called). Very helpful in debugging the app after the first deploy and making sure everything's working as intended.

Would be great to have that as a default for Klaxon.

**Comment by tommeagher** [comment]
I think this is a great idea. I'm a fan of Papertrail as well. And I think this might be as easy as adding it here: https://github.com/themarshallproject/klaxon/blob/develop/app.json#L30-L34

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 5 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
