### ISSUE TITLE
Klaxon sending repeated alerts for website that hasn't changed (gawker.com)

### ISSUE THREAD

**Issue by Srol** [themarshallproject/klaxon#30]
One of our reporters set up an alert for the main content section of gawker.com so they could get an alert if and when it was ever updated or altered. It's been two days since then and Klaxon has sent three alerts for changes, yet the substance of all the alerts don't seem to indicate anything has changed. 

I attached screenshots of all the alerts in question (each one appears to be more or less the same), and of the alert itself in the Klaxon control panel.

![klaxon1](https://cloud.githubusercontent.com/assets/2627023/18401279/c7e5c752-76a7-11e6-93b3-c97f3a23bf14.png)
![klaxon2](https://cloud.githubusercontent.com/assets/2627023/18401280/c7e644f2-76a7-11e6-8e89-5804a42d1833.png)
![klaxon3](https://cloud.githubusercontent.com/assets/2627023/18401281/c7eb00fa-76a7-11e6-891b-9f1ff7b679e7.png)
![screen shot 2016-09-09 at 3 56 10 pm](https://cloud.githubusercontent.com/assets/2627023/18401292/d39c0390-76a7-11e6-8922-0449be77f88a.png)

**Comment by ivarvong** [comment]
Thanks for the issue report! 

My guess is that the CSS selector of "section.main" is not specific enough. Finding the right selector is a bit of an art, but finding something more specific to headlines, without metadata, may help. Does that make sense?

**Comment by Srol** [comment]
It does. I just thought it was weird it was sending these diffs where nothing appeared to be different. I'll give that a try.
