### ISSUE TITLE
Cancel/close the bookmarklet

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#31]
Once you've activated the Klaxon bookmarklet on a page you want to watch, you can't get rid of it and stay on the page without reloading the page. Should we add a cancel/close button?

**Comment by ajshapell** [comment]
@tommeagher I believe this enhancement makes sense to incorporate. I have done so in PR 57, referenced above.

**Comment by tommeagher** [comment]
Closed by pull request #57. Thanks, Ari!
