### ISSUE TITLE
question: which is current stable branch

### ISSUE THREAD

**Issue by bobweston** [themarshallproject/klaxon#316]
I'm trying to revise the original question. Basically, I'm trying to determine which branch is considered the current stable branch. (we would like to bring our install up to date. But I don't want to be on the bleeding edge)

**Comment by bobweston** [comment]
I'm trying to revise the original question. Basically, I'm trying to determine which branch is considered the current stable branch. (we would like to bring our install up to date. But I don't want to be on the bleeding edge)

**Comment by GabeIsman** [comment]
Hey @bobweston,

Sorry for the delay. We consider master to be stable. Nothing is released to master without first running on or own instances for a while. `develop` is also hopefully stable, but you're much more likely to run into trouble automatically deploying develop (which is what we do, so it's not crazy either).

**Comment by bobweston** [comment]
Hi Gabe,

Thank you for that. Much appreciated.

**Comment by tommeagher** [comment]
@bobweston did this answer your question? Is it all right if we close this issue?
