### ISSUE TITLE
Flesh out documentation for deployment via Docker

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#32]
I believe @rdmurphy is working on this [here](https://github.com/themarshallproject/klaxon/blob/master/DOCKER.md). Not sure how much more there is to add, or if it should be referenced explicitly in the main [README](https://github.com/themarshallproject/klaxon/blob/master/README.md).

**Comment by rdmurphy** [comment]
Hello @tommeagher! Figured I'd just move the convo out of the closed pull request to here.

There's definitely more to add, and I think the first step is deciding how Klaxon could interface with Docker Hub. In other words, how do we get it set up as an automated build there? (Basically automates the `docker build` step you'd do if you were prepping it locally, and allows others to just pull down an image that's ready to go.)

I have a fork setup for the [Tribune's instance](https://hub.docker.com/r/texastribune/klaxon/), but it's fairly out of date at this point. And I think if Docker Hub was watching any repo, it probably should be the primary one and not a fork.

A couple options to accomplish this step:
1) The Marshall Project sets up a Docker Hub organization account. On Docker Hub it'd be reachable at `themarshallproject/klaxon`.
2) An individual connects Klaxon to Docker Hub using their personal account. I wouldn't have a problem if it was my Hub account that did so, but it may require me having more permissions on the GitHub side to set things up. (I've done this before, but I need to look into what's involved again.) In this example, it'd be reachable at `rdmurphy/klaxon` on Docker Hub.
3) Another organization steps up and becomes the Docker Hub account steward. `<your-name-here>/klaxon`.

**Comment by tommeagher** [comment]
Hi @rdmurphy. Thanks for this. Option 1 seems like it'd make the most
sense. We haven't used Docker Hub before, so we'll look into this. If we
get stuck or need some advice, we'll ping you. Otherwise, we'll let you
know when this is set up.
-- 
Tom Meagher
Deputy Managing Editor, The Marshall Project
<http://www.themarshallproject.org/>
PGP Public key
<https://themarshallproject-gpg.s3.amazonaws.com/tmeagher.asc>

**Comment by rdmurphy** [comment]
I replied to this nearly five years ago and now I work here, so I guess this is now my responsibility. 😉

**Comment by DOFfactory** [comment]
I just discovered this project, tried to deploy the container with the default settings, the page loads, but I cannot log in with any account (including the default `someuser@companyname.com` from here: https://github.com/themarshallproject/klaxon/tree/develop/docker_example I am getting a 422 page. 

I am self-hosting, and I read (in https://github.com/themarshallproject/klaxon/issues/408) that exposing the page with a reverse proxy through https might help, but what if I do not want to do this? I want only to self-host via http for LAN only? Is there a way how to set klaxon up for this scenario?

**Comment by JoeGermuska** [comment]
It's kind of confusing that there are `Dockerfile`, `docker-compose.yml`, and `DOCKER.md` files in the root of the repository, but also `/docker_example/` with different specifics. 

Can anyone clarify the intentions here?

**Comment by JoeGermuska** [comment]
Just to log, I started a draft PR #547 ... my focus is more on development with Docker than deployment, but it's definitely connected to this one.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 8 years old now) and various components related to Docker, fall in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
