### ISSUE TITLE
Docker environment variables

### ISSUE THREAD

**Issue by bobweston** [themarshallproject/klaxon#321]
Hey all,

Can you tell me if there are Docker env variables I can sub in so we can use postfix and our own mail servers?

(we aren't currently using Sendgrid)

What I'm hoping to do is pass the env parameters that would allow me to build and deploy from your github repo (simply providing the required env parameters when I run the docker container)

**Comment by GabeIsman** [comment]
@bobweston Did you figure this out?

**Comment by bobweston** [comment]
Hey Gabe,

no. I'd be open to suggestions. ;)

**Comment by bobweston** [comment]
Hey Gabe,

  I was able to figure this out. I'll add some information to the docker.md file and do a pull request later.

**Comment by bobweston** [comment]
> @bobweston Did you figure this out?

I've submitted a pull request with some instructions on getting things to work (pretty easily in my view) using docker

**Comment by tommeagher** [comment]
Awesome. Thanks, @bobweston. We'll give it a look!
