### ISSUE TITLE
Unable to load the http/2 gem.

### ISSUE THREAD

**Issue by asvc** [themarshallproject/klaxon#325]
When scheduler executes `bundle exec rake check:all`, the following is returned to the log:
```log
2020-04-15T13:03:47.180932+00:00 app[scheduler.2797]: Unable to load the http/2 gem.
2020-04-15T13:03:47.183215+00:00 app[scheduler.2797]: Unable to load the http/2 gem.
```
Running on "heroku-18" stack, Klaxon v0.3.3.

**Comment by tommeagher** [comment]
I had this same issue come up recently, @GabeIsman, but things still seemed to work.

**Comment by GabeIsman** [comment]
This appears to just be log spam from the [AWS gem](https://github.com/aws/aws-sdk-ruby/issues/1998). Nothing to worry about. It should go away when we get around to upgrading that gem.
