### ISSUE TITLE
The "Creator" field in the Feed doesn't display the user's name

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#33]
![screen shot 2016-09-15 at 2 39 51 pm](https://cloud.githubusercontent.com/assets/713778/18562584/51e832b0-7b52-11e6-8f0d-4756c2795ff0.png)

**Comment by tommeagher** [comment]
This is also empty on the "Watching" page.

**Comment by GabeIsman** [comment]
The data was not being collected on page creation. Fixed in develop.
