### ISSUE TITLE
Sendgrid link to have email confirmed is a broken link

### ISSUE THREAD

**Issue by Sanchovilla** [themarshallproject/klaxon#331]
Hello!  I've clicked on the Sendgrid link to have my email confirmed but it says its a broken link and I'm getting an, "Access to Sendgrid Denied HTTP 403 Error."  Is there another way around this?  I've set-up a free account on Sendgrid but not sure how to make the connection between the two. I hope I'm not screwing up where I'm posting this question. 

_Originally posted by @Sanchovilla in https://github.com/themarshallproject/klaxon/issues/238#issuecomment-622991075_

**Comment by GabeIsman** [comment]
Hey @Sanchovilla,

Sometimes it takes a while for the vendors to set up the associated accounts with Heroku plugins. Maybe give it an hour and try again? You mean the link from the "Resources" tab in Heroku, right?

Gabe

**Comment by Sanchovilla** [comment]
> Hey @Sanchovilla,
> 
> Sometimes it takes a while for the vendors to set up the associated accounts with Heroku plugins. Maybe give it an hour and try again? You mean the link from the "Resources" tab in Heroku, right?
> 
> Gabe

Ahhh okay, that makes total sense.  I'll wait until tonight and give it a go.  Thanks so much for the response, I'm looking forward to using it!

**Comment by Sanchovilla** [comment]
Okay, I let it wait overnight and the link from the resources tab within Heroku was still dead.  I'm going to delete the 1st version of my Heroku account and re-deploy to try again.  I'll also give it a few days before I try to confirm address.  Could be the COVID situation has things running more slowly than usual?

**Comment by GabeIsman** [comment]
@Sanchovilla Did you get this issue resolved?

**Comment by Sanchovilla** [comment]
Hi Gabe!  Thanks, for the follow-up!  I contacted Sendgrid and worked with one of their people that cleared my email address/account.  They were very helpful and it seems to be working. Gracias!  I'm just now starting to really use it and I'm floored by what a useful/awesome tool this is.

**Comment by GabeIsman** [comment]
Great to hear!
