### ISSUE TITLE
Watch URLs programatically?

### ISSUE THREAD

**Issue by danipolo** [themarshallproject/klaxon#332]
I was wondering if it's possible to monitor new URLs programmatically or using an API. I would like to monitor the full life cycle of an article as soon is published on my competitor website. The publisher is posting many articles per day and I would like to add them as soon they are published. Any suggestion?

**Comment by tommeagher** [comment]
Hi @danipolo, this is not currently a feature of Klaxon, though it's something we'd consider adding in the future. We'll tag this as a feature where we'd like some help in case a contributor wants to take this on.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 4 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
