### ISSUE TITLE
Emails can fail silently; consider logging errors?

### ISSUE THREAD

**Issue by ryancatalani** [themarshallproject/klaxon#339]
I noticed today that my installation of Klaxon wasn't sending email notifications. I checked on the web interface and determined that it was still correctly scraping the websites. So my next thought was to check the email provider (Sendgrid). I manually ran `rake check:all`, but didn't see any errors. I still had a feeling the issue was with Sendgrid, so I drilled down into the code and discovered this line:

https://github.com/themarshallproject/klaxon/blob/8f1d6383597aded7935ad45250565b63535e2d7f/app/models/change.rb#L26

When I manually ran that line in the Rails console, without `rescue nil`, it finally came up with an authentication error. I updated the Sendgrid credentials and it's working properly now.

Regarding that line in `change.rb`, it'd be great to at least log the error to make future debugging easier.

**Comment by tommeagher** [comment]
@ryancatalani thanks for raising this. When you said you updated the credentials, what did that process entail? Did you create a new password and add it as a `heroku config` envvar? Or was there something else you needed to do to get things working?

**Comment by ryancatalani** [comment]
@tommeagher For some reason, I couldn't update the password — I'm wondering if this is because I provisioned the Sendgrid account through Heroku. Instead, I generated an API key and set it as the `SENDGRID_PASSWORD` config var. For that to work, you also need to set `SENDGRID_USERNAME` to `apikey`.

**Comment by GabeIsman** [comment]
Hmm, yea I'm seeing the same issue on our instance. The fix you mentioned works as well. I wonder if Sendgrid changed it's authentication process and forgot to update the Heroku plugin? I'll look into it.

**Comment by GabeIsman** [comment]
Btw, very sensible suggestion @ryancatalani. I've implemented it here: 088f514255d97731f0a444aa54975d930c9c4ce2. Sorry to make your debugging harder!

**Comment by ryancatalani** [comment]
No problem, @GabeIsman. Thanks for the quick turnaround on this!
