### ISSUE TITLE
Finish wiring in the stats dashboard on a snapshot page.

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#34]
![screen shot 2016-09-15 at 2 52 55 pm](https://cloud.githubusercontent.com/assets/713778/18563062/27da60ea-7b54-11e6-802a-9ea51f64664b.png)

**Comment by GabeIsman** [comment]
There isn't an easy way to actually calculate this, although it does seem useful. I've removed it for now.
