### ISSUE TITLE
Slack/Discord webhooks stopped working

### ISSUE THREAD

**Issue by immewnity** [themarshallproject/klaxon#344]
Hi all,

I realize this likely isn't a Klaxon issue in itself, but has anyone else had issues with their webhooks not showing any updates? Last push came on 28 May here, while viewing from the Klaxon interface shows several changes since then. No changes were made on my channels that the webhooks would share to, nor the Klaxon instance itself, and I can't find any technical issues on Discord/Slack/Heroku's ends that might've caused this...

**Comment by tommeagher** [comment]
@immewnity, is this just that your Slack stopped working? Are you getting Sendgrid emails? It's not related to [this issue](https://github.com/themarshallproject/klaxon/blob/develop/SENDGRID.md), is it?

**Comment by immewnity** [comment]
I'm still getting the login emails when requested, so it doesn't appear to be related.

**Comment by tommeagher** [comment]
That is odd. We haven't heard reports of this, and our Slack hooks are still working. Is there any hint in your heroku logs?

**Comment by immewnity** [comment]
Ah, yep, there's the error... wish it were more descriptive. (censored sensitive data in the error message)

`2020-06-02T02:53:56.861559+00:00 app[scheduler.1819]: slack_integration#send_notification #etc

2020-06-02T02:53:56.951429+00:00 app[scheduler.1819]: Error sending webhook to url=https://discordapp.com/api/webhooks/87654321/DiScOrD-HoOk/slack for payload={"username":"Klaxon","icon_url":"http://myklaxoninstance.herokuapp.com/assets/klaxon-logo-100px-c4c978b074949e6706cc0bc17d59e0260b7ee3c22c7249ae0cb743e7c2cd9501.png","channel":"#etc","text":"Heroku Test changed http://myklaxoninstance.herokuapp.com/changes/page/16940"}`

Looks like the issue is probably on Discord's end - will give an update if I find anything out from them.

**Comment by tommeagher** [comment]
I haven't really used Discord, so I can't be much help there. Let us know how this winds up.

**Comment by immewnity** [comment]
Still haven't heard from Discord, but wanted to update that I made a test Slack and it works fine, so even more likely that there's a problem on Discord's end.

**Comment by tommeagher** [comment]
@immewnity thanks for the update. If it's all right, we'll close out this issue then. If it resurfaces or if you have further issues, let us know and we can reopen it.

**Comment by immewnity** [comment]
Verified that the above change fixes the issue.

**Comment by tommeagher** [comment]
@immewnity with the new release, did that sort out all the issues? I'm not that familiar with Discord. Is there anything else you think we should do to support the platform? Or should we make note of it in our docs somewhere?

**Comment by immewnity** [comment]
Yes, it works in the new release after #360 .

Discord is very, very similar to Slack, and due to that similarity, Discord has a compatibility mode for webhooks. To use a Slack webhook with Discord, you just append /slack to the end of the Discord webhook URL. It might be something worth noting - I'll write something up and add it to README.md.
