### ISSUE TITLE
Remove or reword "Watch your first item" box after first klaxon is set up

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#36]
![screen shot 2016-09-15 at 2 55 02 pm](https://cloud.githubusercontent.com/assets/713778/18563119/70af0956-7b54-11e6-8bfd-09877951e7a2.png)

After I'm already watching items, it should no longer say "watch your first item".

That box also appears at the top of the help page for some reason.

**Comment by GabeIsman** [comment]
Mostly this was a byproduct of not properly attaching user information to pages. Fixed in develop.
