### ISSUE TITLE
Sendgrid - banned?

### ISSUE THREAD

**Issue by bobburgers7** [themarshallproject/klaxon#361]
Hi,

I tried to setup klaxon via heroku. 

I get to the part about enabling send grid. I click on the link for it on the resources page and it tries to go to send grid. I end up with an empty page loaded. Then, I tried removing the send grid add on and adding it myself manually. I then get this error when I try to add back sendgrid:

'Item could not be created: An error was encountered when contacting the add-on partner to create sendgrid:starter: Error Provisioning User - User status - banned'

Am I doing something wrong? or perhaps send grid no longer allows auto-provisioning its service?

**Comment by bobburgers7** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/41246074/87399600-73503e80-c56c-11ea-8afd-be6de54b633e.png">

**Comment by bobburgers7** [comment]
I completely deleted my klaxon and set it up a 2nd time. I'm using a gmail address when registering with heroku. Now I get a 403 error when trying to click on sendgrid in resources.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/41246074/87401406-ef4b8600-c56e-11ea-8d38-2f1bd7e9513e.png">

**Comment by GabeIsman** [comment]
I've seen this happen before. I think sometimes it just takes sendgrid a little while to set up the account associated with the heroku addon. Try again in a few hours and see if it still gives you the 403. If it does, there might be something else wrong. Sorry for the trouble!

**Comment by bobburgers7** [comment]
I just tried it now (2 days later) and continue to get the  access to sendgrid.com denied error. I opened a ticket w/ Heroku and they've forwarded it to sendgrid. Will see what they say!

**Comment by immewnity** [comment]
Yeah, I've been getting this as well. I think SendGrid may have changed their URL structure and the Heroku integration hasn't been updated. For what it's worth, I've noticed that about half of the time, email works out of the box - so if I spin up an instance and email doesn't work, I've just been removing it and trying again, as one or two more times usually works fine.

**Comment by tommeagher** [comment]
Hey, @bobburgers7, have you had any luck with getting this resolved?

**Comment by mdo1234** [comment]
I have the same problem. After getting the app ready and contacting Sendgrid, Sendgrid tells me they can't find an account associated with my Klaxon installation on Heroku. I deleted the installation, tried again ... to no avail. Any thoughts?

**Comment by mdo1234** [comment]
Okay, I first tried with a .de email address. I retried it with a .com email address and now everything worked fine after getting in touch with Sendgrid's customer serivce.

**Comment by tommeagher** [comment]
Hi @mdo1234. Thanks for checking in on this and on the update. Sendgrid has been increasingly erratic. Many users have no problems at all. We've now heard from a half-dozen in recent months that have had to jump through all kinds of hoops. It seems with their acquisition by Twilio, they're not really set up to support the Heroku accounts the way they used to. We've added this to our README: 
> Unfortunately our email provider Sendgrid now requires an additional step to confirm that you are not a spammer. Your new Sendgrid account is now in a "suspended" state, and to get it unsuspended you have to contact Sendgrid support. You can do this by clicking the Sendgrid logo on the Resources tab. If clicking on the logo takes you to an error page, do not worry. This has been known to happen as Sendgrid's system has undergone redesigns. Instead, go to Sendgrid's page to ask for support. Be sure to use the same email address associated with your Heroku account and provide the url of your Klaxon instance. When they ask for "Business impact," choose "P3 General - You have a question about Sendgrid or how to use its products". This step is a nuisance, but important. You will not be able to get an email log in to Klaxon until you are cleared by Sendgrid. This usually happens pretty quickly (hours not days).

Still, some people have had to go several rounds with Sendgrid support until they get them to whitelist their Klaxon. I'm sorry for the trouble. At some point we'll need to start looking for alternative email providers if this keeps up. 

Glad you got it sorted and are now up and running with your Klaxon.

**Comment by mdo1234** [comment]
@tommeagher I was to quick with my assessment. Klaxon is all set-up, Sendgrind connected. But Klaxon is not transferring an email with the login link. It says "Email Sent. Check your email and find the link to log in to Klaxon" but this is simply not happening ... not in the spam, not anywhere. I am stuck.

**Comment by tommeagher** [comment]
@mdo1234 it sounds like maybe Sendgrid isn't working yet after all. Perhaps @GabeIsman can offer advice.

**Comment by mdo1234** [comment]
From the log

<< 2020-11-07T12:57:42.386628+00:00 app[web.1]: [ActiveJob] [ActionMailer::DeliveryJob] [c6dc7fc1-7d50-4f11-aa1f-953d830bc943] Error performing ActionMailer::DeliveryJob (Job ID: c6dc7fc1-7d50-4f11-aa1f-953d830bc943) from Async(mailers) in 320.82ms: Net::SMTPFatalError (550 The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements >>

The sender email is configured, the Sendgrid account validated.

Well, for now, I grabbed the login link from the logfile, logged into the Klaxon app and configured a Slack notification for testing. But this will work only for me, not the newsroom ;-)

**Comment by tszumowski** [comment]
This issue sounds very similar to https://github.com/themarshallproject/klaxon/issues/404. Over there, I had the same success as the issue author. By setting `MAILER_FROM_ADDRESS` to my SendGrid verified Sender Identity address, I got it to work.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 4 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
