### ISSUE TITLE
Feature request: ability to hide user email addresses for non-admins

### ISSUE THREAD

**Issue by immewnity** [themarshallproject/klaxon#374]
I manage a Klaxon instance that's used across a few newsrooms, and I've received messages from a few people asking if there was any way to hide their email address from other users. As of right now, I don't believe that's a possibility.

Maybe a checkbox toggle in the settings for each user to hide their email, or a global "hide all email addresses" checkbox that admins can toggle?

**Comment by tommeagher** [comment]
Hey @immewnity, this is an interesting idea. We've always thought of this as a shared instance within a single newsroom. We never imagined it would be shared across news organizations. 

Out of curiosity, what are the concerns about email addresses? Are your users OK with their names being displayed but not their addressees? 

And where are they seeing their emails? It's just on the /users page, isn't it? Or is it surfaced on other pages I'm not remembering?

**Comment by immewnity** [comment]
It is a really cool setup - we had knowledge-sharing group comprising a few different orgs and created a Klaxon instance for the group, since many of the pages watched would be the same for everyone.

Names are okay, just concern about the email addresses being viewable by others (I don't quite understand the concerns, but folks have messaged me about it).

Yes, just the /users page as far as I'm aware.

**Comment by tommeagher** [comment]
Ok. Good to know. We'll certainly consider it, and if someone wants to hack on this feature, pull requests are gladly accepted.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 4 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
