### ISSUE TITLE
Change app name

### ISSUE THREAD

**Issue by grssnbchr** [themarshallproject/klaxon#379]
I changed the app name in heroku. Now, when I try to login, the emails I get still point to / account for the old app name. Is there something I need to change? Or is this not a supported use case and I need to redeploy the app to give it another name?

**Comment by tommeagher** [comment]
Hi @grssnbchr. This isn't something we've seen done. @GabeIsman may have some advice on how to update Klaxon to account for the new URL. He's away for a bit but can weigh in when he's back online.

**Comment by harrislapiroff** [comment]
I had to log into the Postgres database using a Postgres client to update the domain name in a table.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 4 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
