### ISSUE TITLE
Bookmarklet issues on Safari

### ISSUE THREAD

**Issue by ajschaf** [themarshallproject/klaxon#381]
I've been having issues getting the bookmarklet to work with Safari recently. I upgraded to v0.4.0 but that didn't help.

When I open up the console and try to use the bookmarklet, I get this error:
`Refused to load https://[klaxon deployment dot com]/embed/inject because it does not appear in the script-src directive of the Content Security Policy.`

**Comment by GabeIsman** [comment]
Hey @ajschaf,

That looks like it's a problem with the web page you're trying to create monitoring for. Some sites set a "Content Security Policy" that doesn't allow Klaxon code to run on their page. In cases like these, unfortunately you'll have to set up the monitoring of those pages manually. Check out the "Adding Klaxon Manually" section of the help page in your app. Unfortunately this does require a little understanding of CSS to do effectively, though you can definitely figure it out even if you don't have that.
