### ISSUE TITLE
Proxy  configuration for Docker

### ISSUE THREAD

**Issue by certrik** [themarshallproject/klaxon#407]
Please provide a working way to install via docker locally. 
A way for defining a proxy (TOR, etc) could be very helpful.

**Comment by certrik** [comment]
@GabeIsman 
Please. Klaxon is also very useful if operated on premise with the ability to use an internal smtp server and connecting to the internet via proxies.

**Comment by GabeIsman** [comment]
Hey @certrik, that's a good idea and I can certainly see the utility. Unfortunately we don't use Docker and don't have time right now to support it more fully. If someone wants to get it up and running and send a PR, I'm happy to merge!

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 4 years old now) and various components related to Docker, fall in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
