### ISSUE TITLE
422 Rejected

### ISSUE THREAD

**Issue by tsenilov** [themarshallproject/klaxon#408]
Local install with docker does not work.
I can see starting page "You’ll know first", type email and then error 422 rejected. Tried different emails, several emails.

Nothing helps. The answer is:
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Allocations: 214)
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

How can I resolve this error or skip this token verification?

**Comment by certrik** [comment]
As far I happen to understand up to now it is a problem of not connecting via SSL so the token cannot be verified.

**Comment by tsenilov** [comment]
> As far I happen to understand up to now it is a problem of not connecting via SSL so the token cannot be verified.

You're right. I've solved this by forcing ssl in my compose file and adding klaxon to traefik2 installation. So now it just works.

**Comment by tsenilov** [comment]
But now I'm having another problem. Browsers block klaxon script. I think it is about CORS, have no idea how to bypass this.

**Comment by GabeIsman** [comment]
What website are you trying to use Klaxon on @tsenilov? Some sites have Content Security Policies (CSP) that prevent the injection of outside scripts into the page. For those sites I'm afraid you have to add them manually (see the Readme).
