### ISSUE TITLE
Make email login optional

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#411]
We have been having an increasingly difficult time with setting up new Sendgrid accounts. After some investigation into other options, I've not found anything that's markedly easier. Sending email is what spammers do, so setting up a newly authorized sender account is always going to be seen as risky. To try to keep the first time user experience as simple and frustration-free as possible, I think we should move away from email as the primary means of authentication.

Having an option for a simple username and password login will allow people to get up and running faster, explore Klaxon a bit, and decide for themselves whether they need to invest the time to get email up and running.

**Comment by kratsg** [comment]
Struggling a bit here as I've been waiting for a few days to get my account un-suspended so I can start. It's not as smooth a process as I would've expected. Surprised the integration w/ heroku is more difficult.

**Comment by fourofspades** [comment]
I guess I'm missing something obvious here, but if there was a basic username/password login and you could then set any email SMTP server (e.g. Gmail).

It does feel like SendGrid is a huge weak link in an other nice product.

**Comment by DieselTech** [comment]
With the Twillo Sendgrid plugin not working directly from herokuapp.com and them not answering support emails to get a new account setup, this leaves Klaxon dead in the water. 

I'd suggest making a temporary login during app creation that can be used to create new users and setup feeds into other notification channels. (Slack / Discord).

**Comment by immewnity** [comment]
Got a working Mailgun integration at [/immewnity/klaxon/tree/mailgun](/immewnity/klaxon/tree/mailgun) - this branch also includes the Microsoft Teams integration proposed in #514 and the develop fix in #578 .

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 4 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
