### ISSUE TITLE
Monitor other content types

### ISSUE THREAD

**Issue by immewnity** [themarshallproject/klaxon#414]
Currently, Klaxon monitors changes in HTML inner content. However, this isn't always the way that websites display their data - oftentimes, the data is dynamically loaded using another method, often JSON.

For example, https://www.pokemon.com/us/news/ loads articles using the JSON data at https://www.pokemon.com/us/api/news/ - the article listing isn't available in a GET request from the base page, and so it cannot currently be monitored with Klaxon.

It would be great to use JSON selectors to pull this data, similar to how CSS selectors are used for HTML data.

**Comment by tommeagher** [comment]
Hi @immewnity. Thanks for this suggestion. It's not documented, but Klaxon actually will work on a JSON feed, though it doesn't support JSON selectors. We're using it now on a couple of sites and have found it helpful. You can add the JSON url using the "Manually Watch an Item" button on the "Watching" page, and it should work. Give it a try and let us know how it goes.

**Comment by tomcardoso** [comment]
I just tried testing this, and I'm wondering if this is maybe not working anymore? I just added a page that returns a JSON content type (I left the selector field blank, to be clear), waited for a scrape to execute, and then checked the `watching/pages/{unique_id}/snapshots` page to see if a snapshot had been captured – but it's not showing me any snapshots. Is there anything I need to do beyond what I've already done to capture the JSON?

**Comment by tommeagher** [comment]
Hey @tomcardoso, it is working on our end. We use `body` in the selector, though I can't seem to remember why, but it works. If you're comfortable sharing your URL (you can email it to me), we can try to test it on our Klaxon instance too.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 4 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
