### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#42]
What can we do to make the documentation [for users](https://github.com/themarshallproject/klaxon/blob/master/data/help.md) and for [developers/maintainers](https://github.com/themarshallproject/klaxon/blob/master/README.md) more clear and easier to use? We're hoping our new community can bring fresh eyes to these and offer some suggestions (and pull requests).

**Comment by xaranke** [comment]
Include a TLDR. Most people never read READMEs in their entirety and having a quick summary would be useful.

**Comment by tommeagher** [comment]
@xaranke this is a great idea. What do you think the TLDR should include? Any chance you want to take a stab at writing it?

**Comment by tommeagher** [comment]
Addressed in 17343276331f97f8367d3f4c9a815a2c32321657. Thanks, @jacksongs!
