### ISSUE TITLE
Unable to deploy to Heroku using link in README

### ISSUE THREAD

**Issue by tszumowski** [themarshallproject/klaxon#422]
I clicked the top Deploy to Heroku link in the README: https://heroku.com/deploy?template=https://github.com/themarshallproject/klaxon/tree/master.

When I deploy the app, I get errors in the "Build App" stage. It says:

```
-----> Building on the Heroku-20 stack
-----> Ruby app detected
-----> Installing bundler 1.17.3
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.5.7.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.5.7.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
 !
 !     The Ruby version you are trying to install does not exist on this stack.
 !     
 !     You are trying to install ruby-2.5.7 on heroku-20.
 !     
 !     Ruby ruby-2.5.7 is present on the following stacks:
 !     
 !     - cedar-14
 !     - heroku-16
 !     - heroku-18
 !     
 !     Heroku recommends you use the latest supported Ruby version listed here:
 !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     
 !     For more information on syntax for declaring a Ruby version see:
 !     https://devcenter.heroku.com/articles/ruby-versions
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

```

Screenshot:
![image](https://user-images.githubusercontent.com/10282962/104637217-80143300-5672-11eb-938b-5c8952af71ab.png)

**Comment by tszumowski** [comment]
Note: Seems related to this issue, just one more version bump in heroku-stack now:
https://github.com/themarshallproject/klaxon/issues/202

**Comment by GabeIsman** [comment]
Hey @tszumowski, Thanks for the detailed issue. I've just upgraded the ruby version in develop, but I want to let that run for a few hours to make sure we've not introduced any new problems. I'll cut a new release to master tomorrow.

If you're eager to get going you can deploy the develop branch here: https://heroku.com/deploy?template=https://github.com/themarshallproject/klaxon/tree/master

**Comment by tszumowski** [comment]
@GabeIsman That link worked perfectly. Thank you!
