### ISSUE TITLE
[Question] Do I need an existing Sendgrid account

### ISSUE THREAD

**Issue by KrisPetkov** [themarshallproject/klaxon#427]
Hello everyone,

I have a question (maybe a dumb one) in reagrds to Sedngrid. Do I need to make a profile before setup the Klaxon on the Heroku platform or the sendgrid account will be created for me after I setup Klaxon application?

Thank you in advance!

**Comment by GabeIsman** [comment]
@KrisPetkov You don't need an existing sendgrid account. One will be created automatically by Heroku in the setup process. There are however lots of annoying details with sendgrid, so be sure to refer to the readme and feel free to come back with questions if you run into trouble.

**Comment by KrisPetkov** [comment]
Hi @GabeIsman  thank you for your answer! I did everything from the github readme and contacted the Sendgrid’s support to unblock my user and they told me that they cannot find a user with this email. I sent them the email used to login in Heroku as described in the tutorial
