### ISSUE TITLE
Add functionality for monitoring files on the web for changes

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#43]
@ivarvong had incorporated this into previous versions of Klaxon and likely has some thoughts on how it might be accomplished here.

**Comment by immewnity** [comment]
The simplest way (in a basic "this file changed" sense) might be to get, store, and compare hashes of each file. MD5 should be more than sufficient in this case, though SHA3 would be the more robust option.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 8 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
