### ISSUE TITLE
Heroku Approaching Row Limit

### ISSUE THREAD

**Issue by tszumowski** [themarshallproject/klaxon#434]
I just got an email regarding my Heroku Klaxon app:

> The database DATABASE_URL on Heroku app [APPNAME]-klaxon is approaching its allocated storage capacity.The database contains 7,483 rows. The Hobby-dev plan allows a maximum of 10,000 rows. If the databases exceeds 10,000 rows then INSERT privileges will be revoked, preventing more data from being written. INSERT privileges are automatically reinstated if rows are removed and the database once again complies with the plan limit
--

I've been running this app for a few weeks, on a few dozen pages. Of which some are a bit chatty (5-10 changes a day). 

Is this Heroku alert normal? If so, is there a way to purge old records in the Heroku database via klaxon UI or code so that I don't hit the limit?

**Comment by tommeagher** [comment]
Hi, Tom. This is common. Once you hit that 10,000-row limit, you can upgrade to the $9/month hobby basic plan for Postgres. But you may not be ready for that yet. 
There isn't a way to delete individual records, unless you want to log into Postgres (and @GabeIsman can advise on that). But it is pretty easy to delete pages you're watching, which will then purge all of their snapshots from the database. There are buttons to the right of every page on the "Watching" page, which you can see here:
<img width="1240" alt="Screen Shot 2021-02-02 at 7 07 08 PM" src="https://user-images.githubusercontent.com/713778/106680133-0f36ab80-658c-11eb-8336-acb00eeae97f.png">

There's also a delete button at the bottom of the edit page for each site you're watching. 
<img width="1201" alt="Screen Shot 2021-02-02 at 7 24 46 PM" src="https://user-images.githubusercontent.com/713778/106680283-57ee6480-658c-11eb-8533-726d3a0cf2fc.png">

Hope this helps. Good luck!

**Comment by tszumowski** [comment]
Thank you @tommeagher. I was interested in what to delete safely from the postgres database.

@GabeIsman I'm able to connect to the database and query tables (as well as backup) below. I did the following and it *seemed* safe. As in I can still see history and I saw the change count on the main page drop after running it. But wanted to check with you. 

1. Get name of database [https://data.heroku.com/](here)
2. Install heroku CLI: `brew tap heroku/brew && brew install heroku`
3. Login: `heroku login`
4. Install Postgress.app using directions [here](https://postgresapp.com/)
5. Add `psql` to CLI as described [here](https://postgresapp.com/documentation/cli-tools.html)
6. Connect to database from CLI: `heroku psql [DATABASE_NAME] --app [APP_NAME]`
7.  View the size of the database, notice `page_snapshots` is the largest.
    ```
    => \dt+
                                            List of relations
    Schema |         Name         | Type  |     Owner      | Persistence |    Size    | Description 
    --------+----------------------+-------+----------------+-------------+------------+-------------
    ...
    public | changes              | table | ylpmwytwxzgujk | permanent   | 424 kB     | 
    public | page_snapshots       | table | ylpmwytwxzgujk | permanent   | 127 MB     | 
    public | pages                | table | ylpmwytwxzgujk | permanent   | 56 kB      | 
    ...
    ```
8. Check some row counts
   ```
    => select count(*) from changes;
    count 
    -------
    4228
    (1 row)

    => select count(*) from page_snapshots;
    count 
    -------
    4306
    (1 row)
   ```
9. Check schema
    ```
    => \d+ page_snapshots
                                                                Table "public.page_snapshots"
    Column   |            Type             | Collation | Nullable |                  Default                   | Storage  | Stats target | Description 
    ------------+-----------------------------+-----------+----------+--------------------------------------------+----------+--------------+-------------
    id         | integer                     |           | not null | nextval('page_snapshots_id_seq'::regclass) | plain    |              | 
    page_id    | integer                     |           |          |                                            | plain    |              | 
    created_at | timestamp without time zone |           | not null |                                            | plain    |              | 
    updated_at | timestamp without time zone |           | not null |                                            | plain    |              | 
    ...

    => \d+ changes
                                                                Table "public.changes"
    Column    |            Type             | Collation | Nullable |               Default               | Storage  | Stats target | Description 
    -------------+-----------------------------+-----------+----------+-------------------------------------+----------+--------------+-------------
    id          | integer                     |           | not null | nextval('changes_id_seq'::regclass) | plain    |              | 
    ...
    created_at  | timestamp without time zone |           | not null |                                     | plain    |              | 
    updated_at  | timestamp without time zone |           | not null |                                     | plain    |              | 
    ...

    ```
10. Backup the database: `heroku pg:backups:capture --app [APP_NAME]`
11. Dangerously(?) delete a bunch of rows
    ```
    DELETE FROM page_snapshots WHERE updated_at <= '2021-02-02';
    ```

**Comment by GabeIsman** [comment]
@tszumowski I think that's relatively safe, but not perfectly efficient, since there are associated `Change` records that are left behind. If you do this through the Rails console instead, that would be handled for you. If you're logged into the [Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli) you can get into the production rails console with `heroku run rails console --app <your instance app name>`. Then you could delete snapshots with `PageSnapshot.where('created_at < ?', 1.month.ago).destroy_all` or some variation. That will preserve data integrity because of the business logic built into the rails models. Obviously use caution! But that's generally the better way to go than directly editing the database.

**Comment by tszumowski** [comment]
@GabeIsman your suggestion is perfect. That's exactly the type of process I was hoping for, and far more safe than me arbitrarily deleting database records from under the hood. Thank you. 😄

**Comment by ilopata1** [comment]
I have found that executing the following SQL is an effective way of keeping only the last change for each page being tracked:

delete from page_snapshots where id not in (select max(id) from page_snapshots group by page_id);
delete from changes where before_id not in (select id from page_snapshots) or after_id not in (select id from page_snapshots);

I would really like to turn this in to a rake task so that I can schedule it, but am not familiar with Ruby on Rails.  Is anyone willing to post the ActiveRecord queries that would accomplish the same result (or even add the task Klaxon)?  This would be a nice way of staying on the free heroku tier for those who dont need to preserve the history of changes.

**Comment by GabeIsman** [comment]
@ilopata1 that's a good suggestion! I'll take a look at that when I have a moment.
