### ISSUE TITLE
Deployment script/instructions for generic Linux box

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#45]
We've chosen Heroku to make this as easy as pie, and some contributors have added Docker support. Where else would you like to deploy this? Can you offer the setup scripts to share with similar users?

**Comment by tommeagher** [comment]
@GabeIsman do you think #88 would address this issue?

**Comment by GabeIsman** [comment]
@tommeagher I think so. Always happy to take more documentation from people who use other setups as well, but I feel as though we have quite a few options now. I'm gonna close this.
