### ISSUE TITLE
Klaxon not checking webpages

### ISSUE THREAD

**Issue by TWALLACK** [themarshallproject/klaxon#454]
I just installed a new instance of Klaxon, but it doesn't seem to be actually finding any changes in web pages.
Is it possible I accidentally screwed up a key setting?  Is there somewhere I can view a list of the correct settings to make sure mine are correct? 

Two notes:
1) SendGrid. I don't think it's a SendGrid problem, because I'm now getting login emails and the feed page is empty.  (I tried unsuccessfully to set up two other instances of Klaxon with fresh settings to try to fix the problem, but SendGrid customer support said they couldn't find my account with the email addresses associated with the Heroku account and don't seem eager to look any further. It took considerable effort from both me and a colleague to persuade SendGrid to activate the first account.)
2) Scheduler. I did set up the Scheduler. It is set to run the rake command (rake check: all) every 10 minutes and appears to be running something.

**Comment by GabeIsman** [comment]
Hi @TWALLACK. I always double check if an instance is working with this page: https://www.timeanddate.com/worldclock/usa/new-york. That should tell you whether it's a problem with the setup of the particular page you're trying to track, or with the instance overall.

**Comment by GabeIsman** [comment]
Do you have the papertrail addon installed? Or another logging addon? You might have a look at the logs and see if there any clues there.

**Comment by TWALLACK** [comment]
Problem solved. I installed the Papertrail addon and was able to identify the problem. Some of the URLs were entered incorrectly, had no updates, or had some other unique situation going on.  Once I corrected some of the URLs, it worked fine. Yay! Thanks for all the great advice.

**Comment by GabeIsman** [comment]
Glad to hear it!
