### ISSUE TITLE
Sendgrid unsuspend

### ISSUE THREAD

**Issue by cmerref** [themarshallproject/klaxon#457]
Hello -- I'm trying to set up Klaxon for my newsroom but I am running into issues with Sendgrid. They can't seem to find my Heroku account I set up with my work email address. This is perhaps the most relevant interaction I have had with them:

"There should be a username used that heroku created when using Sendgrid. It will be a long string of characters@heroku.com."

I cannot find any "long string of characters@heroku.com." 

I followed the Klaxon instructions, set up my Heroku account, etc. This is where I am confused in the Klaxon instructions: "Your new Sendgrid account is now in a "suspended" state, and to get it unsuspended you have to contact Sendgrid support." This is (I think) the first time in the instructions that the creation of a specific Sendgrid account is mentioned for the user. So far the instructions have been about creating a Heroku account. I know virtually nothing about these systems, Heroku and Sendgrid. Maybe in creating a Heroku account a Sendgrid account is also automatically created? I'm confused, as is the Sendgrid support person, as to how to resolve this. As for why Sendgrid support can't find the email address I used to create the Heroku account, I have no idea. 

I'm at a loss and I appreciate any help. Happy to answer any questions to help resolve this.

Thank you,
Clark

**Comment by GabeIsman** [comment]
Hey Clark,

Sorry for the slow reply. The sendgrid account is created for you automatically by the sendgrid heroku plugin when the app is created. I can see my "long string of characters@heroku.com." when I click on the sendgrid plugin in the resources tab of the app. It looks like this:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/697801/114480978-9aa66b80-9bd1-11eb-8751-3de425c26e8a.png">

I'm not sure if you'll be able to see that while your account is suspended. Honestly I don't really know what to tell you. I know this process is a major pain. It's top of our list to make it unnecessary when we have some time to make improvements to Klaxon.

One more option: you can try contacting Heroku support. They might be able to help you locate that email address.

Hope that helps!
Gabe

**Comment by SinSharks** [comment]
@cmerref 
You should be able to find your SendGrid address in your environment variables.
![image](https://user-images.githubusercontent.com/16837202/119102437-ddc4dd00-b9ce-11eb-8825-f2d59f1b6913.png)

@GabeIsman 
Glad to hear as this process is really painful. I'm still struggling through it as well, Hopefully, I'll have some good news in the morning.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 3 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
