### ISSUE TITLE
500 error when logging in

### ISSUE THREAD

**Issue by ericwallace904** [themarshallproject/klaxon#460]
If I try to log in via the bookmarklet or via the app's main page, after I type in my email address and click "login", I get a "500 We're sorry. Something went wrong. Go home?" message.  I'm using Edge on Win10, if that matters.
I checked the Heroku log and there was a message of "Net::SMTPAuthenticationError (535 Authentication failed: Bad username / password"
I hadn't logged in to my Klaxon in a while, if that makes a difference.
I can tell from the logs that it is trying to check my saved pages.

**Comment by tommeagher** [comment]
@ericwallace904 Did this ever work? I wonder if there's an issue with SendGrid authorization.

**Comment by ericwallace904** [comment]
@tommeagher It worked for a while.  It looks like the last notification I got was in May 2020.  I didn't realize it wasn't working until now...

**Comment by tommeagher** [comment]
@ericwallace904 it looks like you're running a very old version of Klaxon, version 0.2.6 (We're now on 0.5.0). I'm going to guess your problem relates to this: https://github.com/themarshallproject/klaxon/blob/develop/SENDGRID.md Did you update your Sendgrid API key as in those instructions?

**Comment by ericwallace904** [comment]
I had not updated my Sendgrid API key - just did that and email works!  Thanks!
I tried updating my Klaxon, and things are breaking because of that mimemagic issue...

**Comment by tommeagher** [comment]
@ericwallace904 Doh. Ok. I will note in #461 you're getting caught in that too. I don't think we'll be able to fix it today, but will try to tackle it early next week.
