### ISSUE TITLE
Use standalone email server instead of Sendgrid

### ISSUE THREAD

**Issue by theRAGEhero** [themarshallproject/klaxon#472]
Hello,
Thank you for this awesome tool. 
I was wondering, is it possible to use a standalone email server?
Thank you and have a good day,
Alessandro

**Comment by danielfomin96** [comment]
It is at least possible with Docker. See [docker_example](https://github.com/themarshallproject/klaxon/tree/develop/docker_example).

**Comment by theRAGEhero** [comment]
Oh Thank you, I didn't see it. 

Il 25 giugno 2021 13:52:52 CEST, danielfomin96 ***@***.***> ha scritto:
>It is at least possible with Docker. See
>[docker_example](https://github.com/themarshallproject/klaxon/tree/develop/docker_example).

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 3 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
