### ISSUE TITLE
Update splash page for newsklaxon.org to indicate release

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#48]
@arossback can tweak this. We probably don't need to move people to the email announcement list. Rather, they can go directly to Github to "Set it up in your newsroom."

The copy at the bottom of the page will need to be updated accordingly.

**Comment by arossback** [comment]
Made some copy changes: https://github.com/themarshallproject/klaxon/commit/30084d87492c943e157eac65263639199845f6a6

**Comment by tommeagher** [comment]
These changes still don't appear to be propogating on newsklaxon.org

**Comment by ivarvong** [comment]
https://newsklaxon.org points at an AWS CloudFront distribution that provides caching and HTTPS. That distribution, `d1fsrxbeh8y22j.cloudfront.net.`, pulls from S3 bucket `tmp-klaxon-marketing`.

I just manually synced the changes on `gh-pages` to S3.
