### ISSUE TITLE
No snapshots displayed, even on constantly changing sites

### ISSUE THREAD

**Issue by NoHara42** [themarshallproject/klaxon#482]
Hi, 
I don't know what could be wrong.

I recieve login emails from sendGrid so there must be something working, but I am seeing no changes on the sites I am watching, nor via email or webhook, and also no snapshots.
See attached screenshot.
![Screenshot from 2021-05-05 12-25-20](https://user-images.githubusercontent.com/43496778/117127937-0c22a580-ad9d-11eb-8257-a528e97462ec.png)

I am watching the constantly changing div on [this website.](https://www.powerthesaurus.org/)
To try and test change detection. To no avail.

The scheduler seems to be running correctly.
![Screenshot from 2021-05-05 12-27-19](https://user-images.githubusercontent.com/43496778/117128110-45f3ac00-ad9d-11eb-8a68-6abaf836d8c4.png)

Could someone give me some tips on how to debug this?

domain: https://impftermin-bot.herokuapp.com/

Many thanks.

**Comment by RoneoOrg** [comment]
Hi,

according to your screenshot, you are watching the div called "`rh_ri`", but this string does not appear in the source code of Powerthesaurus. Maybe this codebase is too inconstant and the div names change too often?

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 3 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
