### ISSUE TITLE
Add screenshots to the documentation

### ISSUE THREAD

**Issue by RoneoOrg** [themarshallproject/klaxon#487]
Hi,

this project is super interesting, and before running the complex setup, I would love to see how it looks:

Quoting from the documentation:

> You list websites you want monitored and Klaxon will visit them and, if they change, email you what's different.

How look the email notifications? and the diff received? A screenshot would be great here!

> Klaxon enables users to "bookmark" portions of a webpage

How does this selection work? With a CSS selector? A screenshot would be great here!

> Click on the button that says “Manage App”. This takes you behind the scenes of the various components powering your Klaxon.

Would love to see that too!  A screenshot would be great here!

Another solution, maybe simplier, could be to make a Screencast / a 'video tour' of Klaxon. That would be lovely, and [Peek](https://github.com/phw/peek) is definitively a valuable tool for that.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 3 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
