### ISSUE TITLE
Send sanity checking alerts

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#496]
We should consider creating some alerts that would go to the list of Klaxon's `ADMIN_EMAILS`. Perhaps once a week (or once a month) send out a note flagging any Pages that have no email subscribers or Slack channels getting alerts. 

Would also be good to send an alert to `ADMIN_EMAILS` for pages that appear to be particularly noisy. If a page generates more than, say, 30 or 50 changes in a day, send a note saying "this might not be useful. Do you want to keep this or delete it? You could also adjust the selector to watch a smaller bit of the page to try to make the changes more meaningful." 

We've seen users who had very noisy Pages kicking off a lot of changes but no one was subscribed to get alerts and so they didn't know until Heroku warned them they had filled up their database.

**Comment by myersjustinc** [comment]
I like this idea. It also seems like some of the concerns raised elsewhere could be included (optionally) in this list of alerts, such as:

*   Selectors that capture too little (#85, #482), rather than too much as described above
*   Misconfigurations on specific pages (#154, #155)

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 3 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
