### ISSUE TITLE
Tools to clean out old snapshots

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#502]
It might be handy for some users or use cases to have a way to delete old snapshots (see https://github.com/themarshallproject/klaxon/issues/434#issuecomment-886693706). This will allow people who don't need to preserve history to use the Heroku free tools for longer. 

1) I think a rake task that generally cleans out everything older than x date, or older than x in sequence would be useful.
2) It might also be useful to have a "clean snapshots" button that deletes all the old changes on a particular page, without deleting the alert.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 3 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
