### ISSUE TITLE
Bookmarklet is not working on some sites

### ISSUE THREAD

**Issue by avelytchko** [themarshallproject/klaxon#506]
Seems like it's not possible to add page from site via bookmarklet - https://www.ableton.com/en/blog/. Tried in Chrome, Edge and Firefox. Probably JS blocking? Klaxon window just not opening. Working perfect on other sites.

**Comment by GabeIsman** [comment]
Yea looks like that page's content security policy forbids the injection of foreign js. There's some more discussion of this here: https://github.com/themarshallproject/klaxon/issues/83. Ultimately not much we can do about it without major restructuring. You can always watch the page manually, without the bookmarklet.
