### ISSUE TITLE
Include diff in Slack messages?

### ISSUE THREAD

**Issue by knutwannheden** [themarshallproject/klaxon#512]
> I am completely new to Klaxon, so I am sorry if I missed something or my request doesn't make any sense!
> 
> So far I really like what I see! I do some IT related work for a small association which researches the affiliations of politicians and lobbyists in Switzerland. For this purpose a tool like Klaxon would be very useful, as there are many involved organizations which all have their own pages for board of directors, advisors, etc.
>
> I was able to set up Klaxon on Heroku (thanks to the very detailed step-by-step guide!). and the Slack integration.

I have now received my first notification in Slack and have a feature request I would like to propose: I think it would be nice if the Slack message already included the diff for the page that changed. The message may have to be truncated, but I still think it would be very useful to see a "preview" of the diff directly in Slack.

**Comment by tommeagher** [comment]
Hi @knutwannheden. Sorry for the slow response. Thank you for reaching out. We're glad things are going well so far. As we think ahead to what we want to do with Klaxon in the year ahead, we'll definitely keep your idea in mind and will update this issue if we decide to adopt it.

**Comment by tommeagher** [comment]
@knutwannheden  Thanks again for your suggestion. We're asking our users to share more of their insights into how (and whether) they're using Klaxon today. Please take a look at #588. We'd love to hear from you.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 3 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
