### ISSUE TITLE
Scheduler environment for docker

### ISSUE THREAD

**Issue by alfureu** [themarshallproject/klaxon#516]
New user to Klaxon, and I am running it as a docker container. I understand that the scheduler should be set up to 10 minutes. At least this is what the documentation says if you deploy it through Heroku. 

I do not use Heroku, is there a way how to set the scheduler manually? Would it be please possible to provide an environment for this setting?

EDIT: actually, it appears as if in the case of docker container there is no scheduler included. Could you provide a documentation how to do this?

**Comment by DOFfactory** [comment]
Actually, it is really easy to implement this, the `crontab` should be set to something like `*/10 * * * * /usr/lical/bin/rake check:all` inside of the docker container and that's it

Please make it possible to set this through an environment for dockers

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 2 years old now) and others dealing with Docker fall in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
