### ISSUE TITLE
Klaxon doesn't follow 301 redirects -- should it?

### ISSUE THREAD

**Issue by jeremybmerrill** [themarshallproject/klaxon#53]
I had been watching an agency's site that had an HTTP URL. That site implemented HTTPS by default in late October. (Good on the government! :) But a distracting time for me.) The site would issue a 301 for HTTP requests to point to the same URL under HTTPS.

This confused Klaxon. After the redirect was set up, the response body was empty, so my selector didn't match, so the email I got from Klaxon showed only a deletion (no green text). This led to me not getting notification of changes, since the page Klaxon was watching really didn't change (since its response body was empty). It's an easy issue to fix for my particular case -- switch the URL to HTTPS -- but it may take a user a while to realize, especially if their site doesn't update approximately daily as mine did.

Now, you all have certainly thought more about the "theory" of Klaxon, so I don't know if this is expected behavior or not. I can totally see it both ways and want to defer to y'all's thinking.

But if y'all think this is a fixable problem, the [RestClient gem](https://rubygems.org/gems/rest-client/versions/1.8.0) will follow redirects automatically and I think `RestClient.get` would be a drop-in replacement for `Net:HTTP.get` [here](https://github.com/themarshallproject/klaxon/blob/master/app/models/page.rb#L27) -- though behavior with respect to encoding might differ...

**Comment by tommeagher** [comment]
Jeremy, thanks for flagging this issue. It's come up again on us recently, so I think we'll want to tackle this question sooner rather than later.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 8 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
