### ISSUE TITLE
special-case the CSS selector generator for <tables>?

### ISSUE THREAD

**Issue by jeremybmerrill** [themarshallproject/klaxon#56]
Hey y'all,

I've noticed wonky behavior when trying to set up an alert for a table. Often, the only visible space in the table is a bunch of <tr> elements. When I set up an alert using `tr` as the selector (possibly with additional context, like `.whatever #whatever tr`), the output looks pretty bad. If I fix it to be `table`, everything works perfectly. I wonder if it'd be worthwhile to special-case the thing that generates CSS selectors to automatically select the parent table if the user has clicked on a `tr`.

(I guess the problem here is that the user's click is ambiguous -- do they want to watch the whole table, that one row, or that one cell? But that's a theoretical problem.)

I should clarify that I haven't tested this and there may be problems I'm not foreseeing. Obviously I defer to y'all if you've thought about this case. And, at the risk of repeating myself, I'm a big fan of Klaxon and thank you all for your work! Klaxon works super well and we're using it a ton. :)

**Comment by tommeagher** [comment]
@jeremybmerrill, we're thrilled to hear you're using it a ton. This is an interesting issue, and one we can ponder a bit. It's definitely an art to getting the right selector, and it's hard to guess sometimes what the user really wants, as you point out. We'll give this a little thought. 

We're hoping after the new year to iron out a lot of these open issues and bugs to prepare a new release ahead of NICAR, so we'll keep this in the mix with that for now. Thanks again for raising it, and please keep any other questions or bug alerts coming.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 8 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
