### ISSUE TITLE
Feed only updates after manually selecting 'latest change' on web

### ISSUE THREAD

**Issue by RidleyJG** [themarshallproject/klaxon#560]
I'm running into an issue where the Klaxon Feed will only update with new entries once I've clicked on a watched item's 'latest change' button within the web interface of the application. Heroku's log appears to show the app working as intended, though no changes are being sent to the Feed automatically, and therefore Slack and Discord notifications no longer function. Any ideas welcome, thanks.

**Comment by immewnity** [comment]
Is the rake functioning running every 10-ish minutes?

**Comment by RidleyJG** [comment]
It is, yeah. Every 10 minutes. I also set up a new rake command on a hobby dyno but same issue, so I went back to the free dyno option and the issue persists, unfortunately. Klaxon has been working as intended for around 2 years now, but suddenly ran into this issue on a few days ago.
