### ISSUE TITLE
Heroku alternatives

### ISSUE THREAD

**Issue by ajschaf** [themarshallproject/klaxon#576]
Heroku will [no longer be offering](https://blog.heroku.com/next-chapter) free dynos or postgres as of Nov. 28, 2022. Are there any other options for Klaxon users?

**Comment by tommeagher** [comment]
Hi @ajschaf. Thanks for raising this issue. We saw the news today as well. In the immediate term, we don't have plans to find a Heroku alternative, but we haven't had a chance to really process it yet. For heavy Klaxon users, the free tiers of Heroku generally didn't last very long, so we had advised folks they would want to consider upgrading to the $7 a month plan. 

We'll need to consider this and think through what the change means for the larger project overall, along with the general disintegration of Sendgrid as a viable option for new users (#404).

**Comment by tommeagher** [comment]
@ajschaf we're continuing to explore options for what this means for Klaxon users, along with Sendgrid's many problems. We're asking our users to share more of their insights into how (and whether) they're using Klaxon today. Please take a look at #588. We'd love to hear from you.

**Comment by r-mcilwain** [comment]
I have proposed Klaxon to the [wishlist](https://github.com/YunoHost/doc/compare/master...r-mcilwain:doc:patch-1) of [Yunohost](https://yunohost.org/en/install), which offers the simplicity of a Heroku install with the added benefit that it is self-hosted.

**Comment by tommeagher** [comment]
We've heard from a lot of our users, but we have not yet found a viable free alternative to Heroku at this point, so we're advising those who have been using those tiers to upgrade to the least expensive services Heroku offers, which will run about $10/month for dynos and Postgres. More details on how to do it are here: https://github.com/themarshallproject/klaxon/blob/develop/HEROKU_UPGRADE.md
