### ISSUE TITLE
Can't use bookmarklet when not signed into Klaxon

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#58]
If you're not signed into a Klaxon session, the bookmarklet will take over a page, but the right sidebar won't appear, so you can't save or close.
The preferred behavior would be for that sidebar to pop up with a signin box that would then reload the page (and bookmarklet) for you.

**Comment by GabeIsman** [comment]
This now loads the login page (on develop). The reload behavior is not yet implemented.

**Comment by GabeIsman** [comment]
This is fixed on develop.
