### ISSUE TITLE
First comparison of snapshots for a page returns 500 error

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#64]

**Comment by GabeIsman** [comment]
This was happening because the database had a pending migration that was causing an after_create hook to error out. So the second time you view the change, it already exists, and the hook doesn't run, and hence, doesn't error. Fixed now.

**Comment by GabeIsman** [comment]
This is still not fixed h/t @tommeagher .

It seems to be a problem related to turbolinks. I can only reproduce when I click 'Past Snapshots' from the change page, and then click 'Compare'. If I reload the snapshots page before clicking 'Compare' it works. Disabling turbolinks resolves this problem.

Looking for solutions now.
