### ISSUE TITLE
Can't log in; no login email

### ISSUE THREAD

**Issue by chrismp** [themarshallproject/klaxon#643]
When I go to the home page for my Klaxon project and enter my email to get the login link, it does not arrive in my inbox. It is not in my spam folder.

How do I troubleshoot the problem?

**Comment by mikejanssen** [comment]
Yep, I've also started having this problem.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
