### ISSUE TITLE
Feature: add toggle in bookmarklet to decide which URL to use

### ISSUE THREAD

**Issue by immewnity** [themarshallproject/klaxon#664]
Currently, the "Add to Klaxon" bookmarklet uses the og:url if available, then looks at the canonical link, then finally the URL as shown in the URL bar (https://github.com/themarshallproject/klaxon/blob/a05d957ad656819b4422f77f20796593aa857f24/app/views/embed/inject.js.erb#L20-L45). I've run into a scary-high number of sites where the og:url is present, but points to the top level of the website instead of the actual page requested (e.g. if https://www.example.org/pages/important-page has an og:url of https://www.example.org/). Of course, the og:url and the canonical link are useful in most cases to get rid of unnecessary parameters and such.

It would be useful to provide something like a radio button selector for each unique URL, so that the user can determine which should be utilized.

(this doesn't seem too terribly hard to make happen, as I don't think it'd involve any database changes, but putting it here in case someone has the time to make it happen before I do)

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
