### ISSUE TITLE
Announce v0.6.0 in the mailing list

### ISSUE THREAD

**Issue by captn3m0** [themarshallproject/klaxon#673]
Since the new release is a new release in a long time, it ought to be announced everywhere!

I checked https://groups.google.com/g/news-klaxon-users, and didn't see it.

**Comment by tommeagher** [comment]
I announced v0.6.0, along with the new release of [Klaxon Cloud](https://www.themarshallproject.org/2023/12/04/documentcloud-upgraded-klaxon-site-monitoring-tool).
