### ISSUE TITLE
Is the number of changes being counted correctly?

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#74]
The change page for a Klaxon alert states how many times a page has changed, like this: 

![screen shot 2017-01-25 at 12 43 48 pm](https://cloud.githubusercontent.com/assets/713778/22302267/093180d2-e2fc-11e6-80a7-f6a2730d2e6f.png)

But when I look at the number of snapshots, I see this: 
![screen shot 2017-01-25 at 12 43 59 pm](https://cloud.githubusercontent.com/assets/713778/22302286/17fc8972-e2fc-11e6-8836-2dac20d29de9.png)

That would say to me that it has changed one time since I started watching it, with the first snapshot being the baseline. Am I misunderstanding that, or is the first snapshot actually the first change and we're missing the baseline?

**Comment by GabeIsman** [comment]
Good catch, looks like it's just counting the number of snapshots.

**Comment by GabeIsman** [comment]
Fixed on develop.
