### ISSUE TITLE
No "delete" button to remove a watched page?

### ISSUE THREAD

**Issue by arm5077** [themarshallproject/klaxon#75]
As best I can tell, there's no way to remove a page from the list of monitored sites within the GUI. 

I've made do by clearing the URL, and I suppose I could delete the entry by jumping into the database, but am I missing something?

**Comment by GabeIsman** [comment]
Hey @arm5077,

Thanks for trying out Klaxon!

This was missing from the initial release and has been added to the forthcoming 0.2.0 release. Which should be out early next week (or you can test it out now by deploying the develop branch).
