### ISSUE TITLE
Evaluate switching away from SendGrid

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#77]
SendGrid is very slow to deliver emails. This is terrible UX for a login email. This is apparently a matter of policy for them: https://sendgrid.com/docs/Classroom/Send/When_Emails_Are_Sent/seeing_a_delay_with_your_first_few_sends.html

Should we be using Postmark or something similar that doesn't have this drawback?

**Comment by tommeagher** [comment]
Gabe, Postmark is out of the Heroku game, and the SendGrid emails have been fairly speedy of late. In that light, is this still something we want to move away from? Are there other decent options apart from Postmark?

**Comment by GabeIsman** [comment]
Mailgun has a free heroku offering as well. No idea what the quality is. I say we table this for now.
