### ISSUE TITLE
Wrong number of changes in email

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#80]
This is related to #74, I suspect. In the emails, it's giving us the wrong number of changes by counting the original, baseline snapshot.

![screen shot 2017-01-31 at 6 09 30 am](https://cloud.githubusercontent.com/assets/713778/22462610/fc22bbe8-e77b-11e6-8dc2-f1b00eb20ee3.png)

**Comment by GabeIsman** [comment]
Fixed on develop.
