### ISSUE TITLE
Search the diffs

### ISSUE THREAD

**Issue by tommeagher** [themarshallproject/klaxon#81]
A reporter asked me yesterday if there was a way to search through the collected snapshots to find the first appearance of a word or phrase. Right now, I do this by manually diffing two snapshots. It would be great to make this searchable in some way.

**Comment by smbsimon** [comment]
+1 on this. Just swung by to share that we'd love to be able to set up specific alerts for keywords.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (7 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
