### ISSUE TITLE
Unable to monitor Twitter users for changes

### ISSUE THREAD

**Issue by Srol** [themarshallproject/klaxon#83]
This could be one or two issues, but I thought it better to write them up as one. Our reporters wanted to use Klaxon to potentially monitor Twitter users for changes in their bios (especially since the service bioischanged.com recently shut down). We were unable to do this for two reasons:

1. The Klaxon bookmarklet does not unfurl on Twitter user pages.
2. Manually adding a page seems to detect nothing when changes are made.

With regard to the bookmarklet, we tested this in Chrome with extensions on and off, as well as in incognito mode and could not get it to unfurl. 

After that, I tried to manually watch [my own Twitter account](http://twitter.com/phogan) using the CSS selector "div#user_description" and made some changes to see if Klaxon would detect them. I changed my bio from: 

```
<div name="user[description]" id="user_description"
    class="ProfileHeaderCardEditing-editableField rich-editor u-borderUserColorLight" contenteditable="true" spellcheck="true"
    aria-multiline="true" data-placeholder="Bio" role="textbox" tabindex="2">Emerging media @Fusion. I know a secret. PGP key: https://keybase.io/phogan</div>
```

to

```
<div name="user[description]" id="user_description"
    class="ProfileHeaderCardEditing-editableField rich-editor u-borderUserColorLight" contenteditable="true" spellcheck="true"
    aria-multiline="true" data-placeholder="Bio" role="textbox" tabindex="2">Emerging media @Fusion. test string. I know a secret. PGP key: https://keybase.io/phogan</div>
```

But Klaxon did not detect this, or subsequent changes I made. I can see in the Heroku logs that it is checking the page for changes, but it doesn't seem to be finding any.

```
downloading url=https://twitter.com/phogan for page.id=7
  PageSnapshot Load (14.6ms)  SELECT  "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."sha2_hash" = $1 AND "page_snapshots"."page_id" = 7 LIMIT 1  [["sha2_hash", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"]]
   (0.4ms)  BEGIN
  SQL (0.6ms)  UPDATE "page_snapshots" SET "updated_at" = '2017-01-31 20:46:46.209892' WHERE "page_snapshots"."id" = $1  [["id", 8]]
   (1.3ms)  COMMIT
page id='7' has not changed
```

**Comment by GabeIsman** [comment]
Hey @Srol,

Thanks for the bug report! I'll take a look at this.

**Comment by GabeIsman** [comment]
It looks like the bookmarklet isn't loading because it violates Twitter's CSP:

```
(unknown) Refused to load the script 'https://the-marshall-project-klaxon.herokuapp.com/embed/inject' because it violates the following Content Security Policy directive: "script-src https://connect.facebook.net https://cm.g.doubleclick.net https://ssl.google-analytics.com https://graph.facebook.com https://twitter.com 'unsafe-eval' https://*.twimg.com https://api.twitter.com https://analytics.twitter.com https://publish.twitter.com https://ton.twitter.com https://syndication.twitter.com https://www.google.com https://t.tellapart.com 'nonce-bQAza99spauOdCOJYcs8aw==' https://platform.twitter.com https://www.google-analytics.com 'self'".
```

That doesn't explain why adding it manually isn't working though...

**Comment by GabeIsman** [comment]
@Srol It looks like what's happening is that that selector only applies when you are logged in as the user and editing your profile. A more appropriate selector might be `.ProfileHeaderCard`. Can you give that a shot and let me know if it works?

**Comment by GabeIsman** [comment]
I think there are a couple of takeaways from this:

1) It would be awesome to get around CSPs somehow. Need to do a little research on this, but a chrome extension would certainly do the trick. Maybe there's a clever way to fetch the javascript and then eval it or something dirty like that.

2) There should be better feedback on a) whether the selector is found on the page, and b) what text is found. This could appear on the 'Page' page, ideally moments after creating a new page manually.

I will file bugs accordingly.

**Comment by Srol** [comment]
Thanks for looking into this @GabeIsman. I'll give that a shot and report back.

**Comment by Srol** [comment]
That did it!

**Comment by tommeagher** [comment]
👏 thanks @srol for reporting this, and thanks to @gabeismam for
investigating the issue so quickly.
A CSP workaround would be great, and in the meantime, we can improve the
docs to address this issue.
-- 
Tom Meagher
Deputy Managing Editor, The Marshall Project
<http://www.themarshallproject.org/>
PGP Public key
<https://themarshallproject-gpg.s3.amazonaws.com/tmeagher.asc>
