### ISSUE TITLE
Restrictive CSPs prevent Klaxon from loading

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#84]
Twitter.com is a prime example. Thanks to @srol for reporting this in #83.

**Comment by marcohald** [comment]
@GabeIsman do you have news on this Issue ?

**Comment by GabeIsman** [comment]
No, no progress on this. You'll have to add pages with strict CSPs manually.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (over 7 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
