### ISSUE TITLE
Better feedback on matched selectors and text

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#85]
There should be feedback on Klaxon on whether the selector you've given is found on the snapshotted page, and what text exactly is found inside. This would provide a quicker feedback loop in cases where you're adding a page manually, or where the content you're after is behind a login. Thanks to @srol and @yolimartinez for bringing this up. Related to #83.

**Comment by myersjustinc** [comment]
Just heard today about [SelectorGadget](http://selectorgadget.com/), which might come in handy for anyone attempting to implement this.

**Comment by GabeIsman** [comment]
Oh nice find @myersjustinc. That looks very useful (at least the core logic) as a way of improving css selector discovery.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (over 7 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
